//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.8.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Authorize.Dal.HelperClasses;
using Authorize.Dal.FactoryClasses;
using Authorize.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Authorize.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Dmchucvu'.<br/><br/></summary>
	[Serializable]
	public partial class DmchucvuEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<TochucChucvuEntity> _tochucChucvus;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static DmchucvuEntityStaticMetaData _staticMetaData = new DmchucvuEntityStaticMetaData();
		private static DmchucvuRelations _relationsFactory = new DmchucvuRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name TochucChucvus</summary>
			public static readonly string TochucChucvus = "TochucChucvus";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class DmchucvuEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public DmchucvuEntityStaticMetaData()
			{
				SetEntityCoreInfo("DmchucvuEntity", InheritanceHierarchyType.None, false, (int)Authorize.Dal.EntityType.DmchucvuEntity, typeof(DmchucvuEntity), typeof(DmchucvuEntityFactory), false);
				AddNavigatorMetaData<DmchucvuEntity, EntityCollection<TochucChucvuEntity>>("TochucChucvus", a => a._tochucChucvus, (a, b) => a._tochucChucvus = b, a => a.TochucChucvus, () => new DmchucvuRelations().TochucChucvuEntityUsingIdChucvu, typeof(TochucChucvuEntity), (int)Authorize.Dal.EntityType.TochucChucvuEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static DmchucvuEntity()
		{
		}

		/// <summary> CTor</summary>
		public DmchucvuEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public DmchucvuEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this DmchucvuEntity</param>
		public DmchucvuEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Dmchucvu which data should be fetched into this Dmchucvu object</param>
		public DmchucvuEntity(System.Int64 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Dmchucvu which data should be fetched into this Dmchucvu object</param>
		/// <param name="validator">The custom validator object for this DmchucvuEntity</param>
		public DmchucvuEntity(System.Int64 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected DmchucvuEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'TochucChucvu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoTochucChucvus() { return CreateRelationInfoForNavigator("TochucChucvus"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this DmchucvuEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static DmchucvuRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'TochucChucvu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathTochucChucvus { get { return _staticMetaData.GetPrefetchPathElement("TochucChucvus", CommonEntityBase.CreateEntityCollection<TochucChucvuEntity>()); } }

		/// <summary>The Id property of the Entity Dmchucvu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "dmchucvu"."id".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int64 Id
		{
			get { return (System.Int64)GetValue((int)DmchucvuFieldIndex.Id, true); }
			set { SetValue((int)DmchucvuFieldIndex.Id, value); }		}

		/// <summary>The Ten property of the Entity Dmchucvu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "dmchucvu"."ten".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Ten
		{
			get { return (System.String)GetValue((int)DmchucvuFieldIndex.Ten, true); }
			set	{ SetValue((int)DmchucvuFieldIndex.Ten, value); }
		}

		/// <summary>The Trangthai property of the Entity Dmchucvu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "dmchucvu"."trangthai".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Trangthai
		{
			get { return (System.Int16)GetValue((int)DmchucvuFieldIndex.Trangthai, true); }
			set	{ SetValue((int)DmchucvuFieldIndex.Trangthai, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'TochucChucvuEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(TochucChucvuEntity))]
		public virtual EntityCollection<TochucChucvuEntity> TochucChucvus { get { return GetOrCreateEntityCollection<TochucChucvuEntity, TochucChucvuEntityFactory>("Dmchucvu", true, false, ref _tochucChucvus); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace Authorize.Dal
{
	public enum DmchucvuFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Ten. </summary>
		Ten,
		///<summary>Trangthai. </summary>
		Trangthai,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Authorize.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Dmchucvu. </summary>
	public partial class DmchucvuRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between DmchucvuEntity and TochucChucvuEntity over the 1:n relation they have, using the relation between the fields: Dmchucvu.Id - TochucChucvu.IdChucvu</summary>
		public virtual IEntityRelation TochucChucvuEntityUsingIdChucvu
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "TochucChucvus", true, new[] { DmchucvuFields.Id, TochucChucvuFields.IdChucvu }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticDmchucvuRelations
	{
		internal static readonly IEntityRelation TochucChucvuEntityUsingIdChucvuStatic = new DmchucvuRelations().TochucChucvuEntityUsingIdChucvu;

		/// <summary>CTor</summary>
		static StaticDmchucvuRelations() { }
	}
}
