//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.8.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Authorize.Dal.HelperClasses;
using Authorize.Dal.FactoryClasses;
using Authorize.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Authorize.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'HomeShare'.<br/><br/></summary>
	[Serializable]
	public partial class HomeShareEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static HomeShareEntityStaticMetaData _staticMetaData = new HomeShareEntityStaticMetaData();
		private static HomeShareRelations _relationsFactory = new HomeShareRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class HomeShareEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public HomeShareEntityStaticMetaData()
			{
				SetEntityCoreInfo("HomeShareEntity", InheritanceHierarchyType.None, false, (int)Authorize.Dal.EntityType.HomeShareEntity, typeof(HomeShareEntity), typeof(HomeShareEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static HomeShareEntity()
		{
		}

		/// <summary> CTor</summary>
		public HomeShareEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public HomeShareEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this HomeShareEntity</param>
		public HomeShareEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for HomeShare which data should be fetched into this HomeShare object</param>
		public HomeShareEntity(System.Int64 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for HomeShare which data should be fetched into this HomeShare object</param>
		/// <param name="validator">The custom validator object for this HomeShareEntity</param>
		public HomeShareEntity(System.Int64 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected HomeShareEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this HomeShareEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static HomeShareRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Id property of the Entity HomeShare<br/><br/></summary>
		/// <remarks>Mapped on  table field: "home_share"."id".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int64 Id
		{
			get { return (System.Int64)GetValue((int)HomeShareFieldIndex.Id, true); }
			set { SetValue((int)HomeShareFieldIndex.Id, value); }		}

		/// <summary>The Kyhieu property of the Entity HomeShare<br/><br/></summary>
		/// <remarks>Mapped on  table field: "home_share"."kyhieu".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Kyhieu
		{
			get { return (System.String)GetValue((int)HomeShareFieldIndex.Kyhieu, true); }
			set	{ SetValue((int)HomeShareFieldIndex.Kyhieu, value); }
		}

		/// <summary>The Malinhvuc property of the Entity HomeShare<br/><br/></summary>
		/// <remarks>Mapped on  table field: "home_share"."malinhvuc".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Malinhvuc
		{
			get { return (System.String)GetValue((int)HomeShareFieldIndex.Malinhvuc, true); }
			set	{ SetValue((int)HomeShareFieldIndex.Malinhvuc, value); }
		}

		/// <summary>The Solieu property of the Entity HomeShare<br/><br/></summary>
		/// <remarks>Mapped on  table field: "home_share"."solieu".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> Solieu
		{
			get { return (Nullable<System.Int64>)GetValue((int)HomeShareFieldIndex.Solieu, false); }
			set	{ SetValue((int)HomeShareFieldIndex.Solieu, value); }
		}

		/// <summary>The Tenlinhvuc property of the Entity HomeShare<br/><br/></summary>
		/// <remarks>Mapped on  table field: "home_share"."tenlinhvuc".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Tenlinhvuc
		{
			get { return (System.String)GetValue((int)HomeShareFieldIndex.Tenlinhvuc, true); }
			set	{ SetValue((int)HomeShareFieldIndex.Tenlinhvuc, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace Authorize.Dal
{
	public enum HomeShareFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Kyhieu. </summary>
		Kyhieu,
		///<summary>Malinhvuc. </summary>
		Malinhvuc,
		///<summary>Solieu. </summary>
		Solieu,
		///<summary>Tenlinhvuc. </summary>
		Tenlinhvuc,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Authorize.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: HomeShare. </summary>
	public partial class HomeShareRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticHomeShareRelations
	{

		/// <summary>CTor</summary>
		static StaticHomeShareRelations() { }
	}
}
