//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.8.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Authorize.Dal.HelperClasses;
using Authorize.Dal.FactoryClasses;
using Authorize.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Authorize.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Sysdinhdanh'.<br/><br/></summary>
	[Serializable]
	public partial class SysdinhdanhEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysdinhdanhEntityStaticMetaData _staticMetaData = new SysdinhdanhEntityStaticMetaData();
		private static SysdinhdanhRelations _relationsFactory = new SysdinhdanhRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysdinhdanhEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysdinhdanhEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysdinhdanhEntity", InheritanceHierarchyType.None, false, (int)Authorize.Dal.EntityType.SysdinhdanhEntity, typeof(SysdinhdanhEntity), typeof(SysdinhdanhEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SysdinhdanhEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysdinhdanhEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysdinhdanhEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysdinhdanhEntity</param>
		public SysdinhdanhEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysdinhdanh which data should be fetched into this Sysdinhdanh object</param>
		public SysdinhdanhEntity(System.Int64 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysdinhdanh which data should be fetched into this Sysdinhdanh object</param>
		/// <param name="validator">The custom validator object for this SysdinhdanhEntity</param>
		public SysdinhdanhEntity(System.Int64 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysdinhdanhEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysdinhdanhEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysdinhdanhRelations Relations { get { return _relationsFactory; } }

		/// <summary>The CapDinhdanh property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."cap_dinhdanh".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int64 CapDinhdanh
		{
			get { return (System.Int64)GetValue((int)SysdinhdanhFieldIndex.CapDinhdanh, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.CapDinhdanh, value); }
		}

		/// <summary>The CoquanBanhanh property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."coquan_banhanh".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 250.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String CoquanBanhanh
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.CoquanBanhanh, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.CoquanBanhanh, value); }
		}

		/// <summary>The DiaChi property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."dia_chi".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String DiaChi
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.DiaChi, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.DiaChi, value); }
		}

		/// <summary>The Email property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."email".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Email
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.Email, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.Email, value); }
		}

		/// <summary>The Fax property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."fax".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Fax
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.Fax, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.Fax, value); }
		}

		/// <summary>The Id property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."id".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int64 Id
		{
			get { return (System.Int64)GetValue((int)SysdinhdanhFieldIndex.Id, true); }
			set { SetValue((int)SysdinhdanhFieldIndex.Id, value); }		}

		/// <summary>The MaDinhdanh property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ma_dinhdanh".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MaDinhdanh
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.MaDinhdanh, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.MaDinhdanh, value); }
		}

		/// <summary>The MaDvqhns property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ma_dvqhns".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MaDvqhns
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.MaDvqhns, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.MaDvqhns, value); }
		}

		/// <summary>The MaHuyen property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ma_huyen".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MaHuyen
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.MaHuyen, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.MaHuyen, value); }
		}

		/// <summary>The MaTinh property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ma_tinh".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MaTinh
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.MaTinh, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.MaTinh, value); }
		}

		/// <summary>The MaXa property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ma_xa".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MaXa
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.MaXa, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.MaXa, value); }
		}

		/// <summary>The NgayBanhanh property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ngay_banhanh".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> NgayBanhanh
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SysdinhdanhFieldIndex.NgayBanhanh, false); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.NgayBanhanh, value); }
		}

		/// <summary>The NgayHhl property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ngay_hhl".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> NgayHhl
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SysdinhdanhFieldIndex.NgayHhl, false); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.NgayHhl, value); }
		}

		/// <summary>The NgayHl property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ngay_hl".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> NgayHl
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SysdinhdanhFieldIndex.NgayHl, false); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.NgayHl, value); }
		}

		/// <summary>The QdBanhanh property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."qd_banhanh".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 250.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String QdBanhanh
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.QdBanhanh, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.QdBanhanh, value); }
		}

		/// <summary>The SoDienthoai property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."so_dienthoai".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String SoDienthoai
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.SoDienthoai, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.SoDienthoai, value); }
		}

		/// <summary>The TenDonvi property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."ten_donvi".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 250.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String TenDonvi
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.TenDonvi, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.TenDonvi, value); }
		}

		/// <summary>The Website property of the Entity Sysdinhdanh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdinhdanh"."website".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Website
		{
			get { return (System.String)GetValue((int)SysdinhdanhFieldIndex.Website, true); }
			set	{ SetValue((int)SysdinhdanhFieldIndex.Website, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace Authorize.Dal
{
	public enum SysdinhdanhFieldIndex
	{
		///<summary>CapDinhdanh. </summary>
		CapDinhdanh,
		///<summary>CoquanBanhanh. </summary>
		CoquanBanhanh,
		///<summary>DiaChi. </summary>
		DiaChi,
		///<summary>Email. </summary>
		Email,
		///<summary>Fax. </summary>
		Fax,
		///<summary>Id. </summary>
		Id,
		///<summary>MaDinhdanh. </summary>
		MaDinhdanh,
		///<summary>MaDvqhns. </summary>
		MaDvqhns,
		///<summary>MaHuyen. </summary>
		MaHuyen,
		///<summary>MaTinh. </summary>
		MaTinh,
		///<summary>MaXa. </summary>
		MaXa,
		///<summary>NgayBanhanh. </summary>
		NgayBanhanh,
		///<summary>NgayHhl. </summary>
		NgayHhl,
		///<summary>NgayHl. </summary>
		NgayHl,
		///<summary>QdBanhanh. </summary>
		QdBanhanh,
		///<summary>SoDienthoai. </summary>
		SoDienthoai,
		///<summary>TenDonvi. </summary>
		TenDonvi,
		///<summary>Website. </summary>
		Website,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Authorize.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Sysdinhdanh. </summary>
	public partial class SysdinhdanhRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysdinhdanhRelations
	{

		/// <summary>CTor</summary>
		static StaticSysdinhdanhRelations() { }
	}
}
