//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace App.QTHTGis.Dal.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Appqthtgis.appqthtgisGetMenuByUserFuncResult'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the method <see cref="App.QTHTGis.Dal.FactoryClasses.QueryFactory.GetMenuByUserFunc"/>. </remarks>
	[Serializable]
	public partial class appqthtgisGetMenuByUserFuncResultRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="appqthtgisGetMenuByUserFuncResultRow"/> class.</summary>
		public appqthtgisGetMenuByUserFuncResultRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Machucnang field.</summary>
		public System.String Machucnang { get; set; }
		/// <summary>Gets or sets the Tenchucnang field.</summary>
		public System.String Tenchucnang { get; set; }
		/// <summary>Gets or sets the Macha field.</summary>
		public System.String Macha { get; set; }
		/// <summary>Gets or sets the Menuid field.</summary>
		public System.Int64 Menuid { get; set; }
		/// <summary>Gets or sets the Cssclass field.</summary>
		public System.String Cssclass { get; set; }
		/// <summary>Gets or sets the Iconclass field.</summary>
		public System.String Iconclass { get; set; }
		/// <summary>Gets or sets the State field.</summary>
		public System.String State { get; set; }
		/// <summary>Gets or sets the Sothutu field.</summary>
		public System.Int64 Sothutu { get; set; }
	}
}

