//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.8.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Authorize.Dal.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitDangkychiaseEntityMappings();
			InitDmchucvuEntityMappings();
			InitDmphongbanEntityMappings();
			InitDmtochucEntityMappings();
			InitHomeShareEntityMappings();
			InitSysappEntityMappings();
			InitSysattachmentEntityMappings();
			InitSysdinhdanhEntityMappings();
			InitSysdvhanhchinhEntityMappings();
			InitSysdvqhnEntityMappings();
			InitSysgroupEntityMappings();
			InitSysgroupmenuEntityMappings();
			InitSyslogEntityMappings();
			InitSyslogactionEntityMappings();
			InitSysmenuEntityMappings();
			InitSysRefreshtokenEntityMappings();
			InitSystaomaEntityMappings();
			InitSystudienEntityMappings();
			InitSysunitEntityMappings();
			InitSysuserEntityMappings();
			InitSysusergroupEntityMappings();
			InitSysusermenuEntityMappings();
			InitTochucChucvuEntityMappings();
		}

		/// <summary>Inits DangkychiaseEntity's mappings</summary>
		private void InitDangkychiaseEntityMappings()
		{
			this.AddElementMapping("DangkychiaseEntity", @"DATAWAREHOUSEBG", @"appqtht", "dangkychiase", 10, 0);
			this.AddElementFieldMapping("DangkychiaseEntity", "Dieukhoan", "dieukhoan", false, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 0);
			this.AddElementFieldMapping("DangkychiaseEntity", "Donvicongtac", "donvicongtac", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("DangkychiaseEntity", "Email", "email", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("DangkychiaseEntity", "Hoten", "hoten", false, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("DangkychiaseEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 4);
			this.AddElementFieldMapping("DangkychiaseEntity", "Motadulieu", "motadulieu", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("DangkychiaseEntity", "Ngaydangky", "ngaydangky", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("DangkychiaseEntity", "Sodt", "sodt", false, "Varchar", 11, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("DangkychiaseEntity", "Status", "status", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 8);
			this.AddElementFieldMapping("DangkychiaseEntity", "Tendulieu", "tendulieu", false, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 9);
		}

		/// <summary>Inits DmchucvuEntity's mappings</summary>
		private void InitDmchucvuEntityMappings()
		{
			this.AddElementMapping("DmchucvuEntity", @"DATAWAREHOUSEBG", @"appqtht", "dmchucvu", 3, 0);
			this.AddElementFieldMapping("DmchucvuEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("DmchucvuEntity", "Ten", "ten", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("DmchucvuEntity", "Trangthai", "trangthai", false, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 2);
		}

		/// <summary>Inits DmphongbanEntity's mappings</summary>
		private void InitDmphongbanEntityMappings()
		{
			this.AddElementMapping("DmphongbanEntity", @"DATAWAREHOUSEBG", @"appqtht", "dmphongban", 4, 0);
			this.AddElementFieldMapping("DmphongbanEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("DmphongbanEntity", "Ten", "ten", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("DmphongbanEntity", "Trangthai", "trangthai", false, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 2);
			this.AddElementFieldMapping("DmphongbanEntity", "Unitcode", "unitcode", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
		}

		/// <summary>Inits DmtochucEntity's mappings</summary>
		private void InitDmtochucEntityMappings()
		{
			this.AddElementMapping("DmtochucEntity", @"DATAWAREHOUSEBG", @"appqtht", "dmtochuc", 3, 0);
			this.AddElementFieldMapping("DmtochucEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("DmtochucEntity", "Ten", "ten", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("DmtochucEntity", "Trangthai", "trangthai", false, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 2);
		}

		/// <summary>Inits HomeShareEntity's mappings</summary>
		private void InitHomeShareEntityMappings()
		{
			this.AddElementMapping("HomeShareEntity", @"DATAWAREHOUSEBG", @"appqtht", "home_share", 5, 0);
			this.AddElementFieldMapping("HomeShareEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("HomeShareEntity", "Kyhieu", "kyhieu", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("HomeShareEntity", "Malinhvuc", "malinhvuc", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("HomeShareEntity", "Solieu", "solieu", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 3);
			this.AddElementFieldMapping("HomeShareEntity", "Tenlinhvuc", "tenlinhvuc", true, "Varchar", 255, 0, 0, false, "", null, typeof(System.String), 4);
		}

		/// <summary>Inits SysappEntity's mappings</summary>
		private void InitSysappEntityMappings()
		{
			this.AddElementMapping("SysappEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysapp", 6, 0);
			this.AddElementFieldMapping("SysappEntity", "Appid", "appid", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("SysappEntity", "Dinhdanhapp", "dinhdanhapp", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SysappEntity", "Mota", "mota", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SysappEntity", "State", "state", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysappEntity", "Tenapp", "tenapp", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SysappEntity", "Trangthai", "trangthai", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 5);
		}

		/// <summary>Inits SysattachmentEntity's mappings</summary>
		private void InitSysattachmentEntityMappings()
		{
			this.AddElementMapping("SysattachmentEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysattachment", 6, 0);
			this.AddElementFieldMapping("SysattachmentEntity", "Createby", "createby", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SysattachmentEntity", "Createdate", "createdate", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("SysattachmentEntity", "Filename", "filename", true, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SysattachmentEntity", "Filepath", "filepath", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysattachmentEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 4);
			this.AddElementFieldMapping("SysattachmentEntity", "Localfilename", "localfilename", true, "Varchar", 1000, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits SysdinhdanhEntity's mappings</summary>
		private void InitSysdinhdanhEntityMappings()
		{
			this.AddElementMapping("SysdinhdanhEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysdinhdanh", 18, 0);
			this.AddElementFieldMapping("SysdinhdanhEntity", "CapDinhdanh", "cap_dinhdanh", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("SysdinhdanhEntity", "CoquanBanhanh", "coquan_banhanh", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SysdinhdanhEntity", "DiaChi", "dia_chi", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SysdinhdanhEntity", "Email", "email", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysdinhdanhEntity", "Fax", "fax", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SysdinhdanhEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 5);
			this.AddElementFieldMapping("SysdinhdanhEntity", "MaDinhdanh", "ma_dinhdanh", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("SysdinhdanhEntity", "MaDvqhns", "ma_dvqhns", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("SysdinhdanhEntity", "MaHuyen", "ma_huyen", true, "Varchar", 10, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("SysdinhdanhEntity", "MaTinh", "ma_tinh", true, "Varchar", 10, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("SysdinhdanhEntity", "MaXa", "ma_xa", true, "Varchar", 10, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("SysdinhdanhEntity", "NgayBanhanh", "ngay_banhanh", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 11);
			this.AddElementFieldMapping("SysdinhdanhEntity", "NgayHhl", "ngay_hhl", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 12);
			this.AddElementFieldMapping("SysdinhdanhEntity", "NgayHl", "ngay_hl", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 13);
			this.AddElementFieldMapping("SysdinhdanhEntity", "QdBanhanh", "qd_banhanh", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("SysdinhdanhEntity", "SoDienthoai", "so_dienthoai", true, "Varchar", 10, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("SysdinhdanhEntity", "TenDonvi", "ten_donvi", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 16);
			this.AddElementFieldMapping("SysdinhdanhEntity", "Website", "website", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 17);
		}

		/// <summary>Inits SysdvhanhchinhEntity's mappings</summary>
		private void InitSysdvhanhchinhEntityMappings()
		{
			this.AddElementMapping("SysdvhanhchinhEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysdvhanhchinh", 9, 0);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "CapDbhc", "cap_dbhc", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 1);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "MaDbhc", "ma_dbhc", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "MaDbhcCha", "ma_dbhc_cha", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "MaDinhdanhtinh", "ma_dinhdanhtinh", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "Makey", "makey", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "NgayHhl", "ngay_hhl", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "NgayHl", "ngay_hl", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 7);
			this.AddElementFieldMapping("SysdvhanhchinhEntity", "TenDbhc", "ten_dbhc", false, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 8);
		}

		/// <summary>Inits SysdvqhnEntity's mappings</summary>
		private void InitSysdvqhnEntityMappings()
		{
			this.AddElementMapping("SysdvqhnEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysdvqhns", 50, 0);
			this.AddElementFieldMapping("SysdvqhnEntity", "CanCu", "can_cu", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SysdvqhnEntity", "CapNs", "cap_ns", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SysdvqhnEntity", "CapQly", "cap_qly", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SysdvqhnEntity", "CquanTlap", "cquan_tlap", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysdvqhnEntity", "Chudautu", "chudautu", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SysdvqhnEntity", "DonviQl", "donvi_ql", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SysdvqhnEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 6);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaBqlda", "ma_bqlda", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaCap", "ma_cap", true, "Varchar", 1, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaCtmt", "ma_ctmt", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaChuong", "ma_chuong", true, "Varchar", 3, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaDaDp", "ma_da_dp", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaDonVi", "ma_don_vi", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaDvqhns", "ma_dvqhns", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaDvqhnsCha", "ma_dvqhns_cha", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaHuyen", "ma_huyen", true, "Varchar", 3, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaLoaidv", "ma_loaidv", true, "Varchar", 2, 0, 0, false, "", null, typeof(System.String), 16);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaNkt", "ma_nkt", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 17);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaNtt", "ma_ntt", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 18);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaNhomDa", "ma_nhom_da", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 19);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaTinh", "ma_tinh", true, "Varchar", 2, 0, 0, false, "", null, typeof(System.String), 20);
			this.AddElementFieldMapping("SysdvqhnEntity", "MaXa", "ma_xa", true, "Varchar", 5, 0, 0, false, "", null, typeof(System.String), 21);
			this.AddElementFieldMapping("SysdvqhnEntity", "NoiMoTk", "noi_mo_tk", true, "Varchar", 120, 0, 0, false, "", null, typeof(System.String), 22);
			this.AddElementFieldMapping("SysdvqhnEntity", "NvuThien", "nvu_thien", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 23);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgayChuyenDoi", "ngay_chuyen_doi", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 24);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgayHetHl", "ngay_het_hl", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 25);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgayHl", "ngay_hl", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 26);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgayHt", "ngay_ht", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 27);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgayKc", "ngay_kc", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 28);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgayPs", "ngay_ps", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 29);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgayQd", "ngay_qd", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 30);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgaySd", "ngay_sd", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 31);
			this.AddElementFieldMapping("SysdvqhnEntity", "NgayTao", "ngay_tao", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 32);
			this.AddElementFieldMapping("SysdvqhnEntity", "NguoiQly", "nguoi_qly", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 33);
			this.AddElementFieldMapping("SysdvqhnEntity", "NguoiTao", "nguoi_tao", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 34);
			this.AddElementFieldMapping("SysdvqhnEntity", "NguonDl", "nguon_dl", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 35);
			this.AddElementFieldMapping("SysdvqhnEntity", "Shkb", "shkb", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 36);
			this.AddElementFieldMapping("SysdvqhnEntity", "SoQd", "so_qd", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 37);
			this.AddElementFieldMapping("SysdvqhnEntity", "SoTk", "so_tk", true, "Varchar", 120, 0, 0, false, "", null, typeof(System.String), 38);
			this.AddElementFieldMapping("SysdvqhnEntity", "TenDaDp", "ten_da_dp", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 39);
			this.AddElementFieldMapping("SysdvqhnEntity", "TenDvqhns", "ten_dvqhns", true, "Varchar", 240, 0, 0, false, "", null, typeof(System.String), 40);
			this.AddElementFieldMapping("SysdvqhnEntity", "TenNhomDa", "ten_nhom_da", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 41);
			this.AddElementFieldMapping("SysdvqhnEntity", "TinhTrang", "tinh_trang", true, "Varchar", 9, 0, 0, false, "", null, typeof(System.String), 42);
			this.AddElementFieldMapping("SysdvqhnEntity", "TmDtu", "tm_dtu", true, "Numeric", 0, 38, 0, false, "", null, typeof(System.Decimal), 43);
			this.AddElementFieldMapping("SysdvqhnEntity", "TypeDvqhns", "type_dvqhns", true, "Varchar", 2, 0, 0, false, "", null, typeof(System.String), 44);
			this.AddElementFieldMapping("SysdvqhnEntity", "TrangThai", "trang_thai", true, "Varchar", 1, 0, 0, false, "", null, typeof(System.String), 45);
			this.AddElementFieldMapping("SysdvqhnEntity", "TrdNsnn", "trd_nsnn", true, "Numeric", 0, 38, 0, false, "", null, typeof(System.Decimal), 46);
			this.AddElementFieldMapping("SysdvqhnEntity", "TrdOda", "trd_oda", true, "Numeric", 0, 38, 0, false, "", null, typeof(System.Decimal), 47);
			this.AddElementFieldMapping("SysdvqhnEntity", "TrdTpcp", "trd_tpcp", true, "Numeric", 0, 38, 0, false, "", null, typeof(System.Decimal), 48);
			this.AddElementFieldMapping("SysdvqhnEntity", "UserName", "user_name", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 49);
		}

		/// <summary>Inits SysgroupEntity's mappings</summary>
		private void InitSysgroupEntityMappings()
		{
			this.AddElementMapping("SysgroupEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysgroup", 7, 0);
			this.AddElementFieldMapping("SysgroupEntity", "Appid", "appid", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("SysgroupEntity", "Description", "description", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SysgroupEntity", "Groupid", "groupid", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 2);
			this.AddElementFieldMapping("SysgroupEntity", "Groupname", "groupname", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysgroupEntity", "Level", "level", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 4);
			this.AddElementFieldMapping("SysgroupEntity", "Status", "status", true, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 5);
			this.AddElementFieldMapping("SysgroupEntity", "Unitcode", "unitcode", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 6);
		}

		/// <summary>Inits SysgroupmenuEntity's mappings</summary>
		private void InitSysgroupmenuEntityMappings()
		{
			this.AddElementMapping("SysgroupmenuEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysgroupmenu", 3, 0);
			this.AddElementFieldMapping("SysgroupmenuEntity", "Function", "function", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SysgroupmenuEntity", "Groupid", "groupid", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
			this.AddElementFieldMapping("SysgroupmenuEntity", "Menuid", "menuid", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 2);
		}

		/// <summary>Inits SyslogEntity's mappings</summary>
		private void InitSyslogEntityMappings()
		{
			this.AddElementMapping("SyslogEntity", @"DATAWAREHOUSEBG", @"appqtht", "syslogs", 14, 0);
			this.AddElementFieldMapping("SyslogEntity", "ICreateBy", "i_create_by", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SyslogEntity", "ICreateDate", "i_create_date", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("SyslogEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 2);
			this.AddElementFieldMapping("SyslogEntity", "IdModified", "id_modified", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 3);
			this.AddElementFieldMapping("SyslogEntity", "IState", "i_state", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SyslogEntity", "IUpdateBy", "i_update_by", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SyslogEntity", "IUpdateDate", "i_update_date", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 6);
			this.AddElementFieldMapping("SyslogEntity", "Name", "name", true, "Varchar", 300, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("SyslogEntity", "Note", "note", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("SyslogEntity", "RequestBody", "request_body", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("SyslogEntity", "RequestMethod", "request_method", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("SyslogEntity", "ResponseBody", "response_body", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("SyslogEntity", "State", "state", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("SyslogEntity", "Unitcode", "unitcode", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 13);
		}

		/// <summary>Inits SyslogactionEntity's mappings</summary>
		private void InitSyslogactionEntityMappings()
		{
			this.AddElementMapping("SyslogactionEntity", @"DATAWAREHOUSEBG", @"appqtht", "syslogaction", 9, 0);
			this.AddElementFieldMapping("SyslogactionEntity", "Action", "action", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SyslogactionEntity", "Data", "data", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SyslogactionEntity", "DateCreate", "date_create", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 2);
			this.AddElementFieldMapping("SyslogactionEntity", "Id", "id", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SyslogactionEntity", "IpClient", "ip_client", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SyslogactionEntity", "Note", "note", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SyslogactionEntity", "ObjectName", "object_name", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("SyslogactionEntity", "UserId", "user_id", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 7);
			this.AddElementFieldMapping("SyslogactionEntity", "UserName", "user_name", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 8);
		}

		/// <summary>Inits SysmenuEntity's mappings</summary>
		private void InitSysmenuEntityMappings()
		{
			this.AddElementMapping("SysmenuEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysmenu", 12, 0);
			this.AddElementFieldMapping("SysmenuEntity", "Appid", "appid", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SysmenuEntity", "Cssclass", "cssclass", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SysmenuEntity", "Function", "function", true, "Varchar", 30, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SysmenuEntity", "Iconclass", "iconclass", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysmenuEntity", "Macha", "macha", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SysmenuEntity", "Machucnang", "machucnang", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SysmenuEntity", "Menuid", "menuid", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 6);
			this.AddElementFieldMapping("SysmenuEntity", "Sothutu", "sothutu", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 7);
			this.AddElementFieldMapping("SysmenuEntity", "State", "state", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("SysmenuEntity", "Tenchucnang", "tenchucnang", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("SysmenuEntity", "Trangthai", "trangthai", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 10);
			this.AddElementFieldMapping("SysmenuEntity", "Unitcode", "unitcode", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 11);
		}

		/// <summary>Inits SysRefreshtokenEntity's mappings</summary>
		private void InitSysRefreshtokenEntityMappings()
		{
			this.AddElementMapping("SysRefreshtokenEntity", @"DATAWAREHOUSEBG", @"appqtht", "sys_refreshtokens", 13, 0);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Appid", "appid", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Created", "created", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 1);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Createdbyip", "createdbyip", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Expires", "expires", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 3);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 4);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Isactive", "isactive", true, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 5);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Isexpired", "isexpired", true, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 6);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Replacedbytoken", "replacedbytoken", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Revoked", "revoked", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 8);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Revokedbyip", "revokedbyip", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Tag", "tag", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Token", "token", true, "Varchar", 2000, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("SysRefreshtokenEntity", "Userid", "userid", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 12);
		}

		/// <summary>Inits SystaomaEntity's mappings</summary>
		private void InitSystaomaEntityMappings()
		{
			this.AddElementMapping("SystaomaEntity", @"DATAWAREHOUSEBG", @"appqtht", "systaoma", 6, 0);
			this.AddElementFieldMapping("SystaomaEntity", "Dodai", "dodai", true, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 0);
			this.AddElementFieldMapping("SystaomaEntity", "Giatricap", "giatricap", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
			this.AddElementFieldMapping("SystaomaEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 2);
			this.AddElementFieldMapping("SystaomaEntity", "Kyhieubatdau", "kyhieubatdau", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SystaomaEntity", "State", "state", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SystaomaEntity", "Unitcode", "unitcode", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits SystudienEntity's mappings</summary>
		private void InitSystudienEntityMappings()
		{
			this.AddElementMapping("SystudienEntity", @"DATAWAREHOUSEBG", @"appqtht", "systudien", 14, 0);
			this.AddElementFieldMapping("SystudienEntity", "Cap", "cap", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("SystudienEntity", "Cqbanhanh", "cqbanhanh", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SystudienEntity", "Fieldname", "fieldname", false, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SystudienEntity", "Ghichu", "ghichu", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SystudienEntity", "Id", "id", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 4);
			this.AddElementFieldMapping("SystudienEntity", "MaDinhdanhtinh", "ma_dinhdanhtinh", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SystudienEntity", "MaTudien", "ma_tudien", false, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 6);
			this.AddElementFieldMapping("SystudienEntity", "Ngaybanhanh", "ngaybanhanh", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 7);
			this.AddElementFieldMapping("SystudienEntity", "Qdbanhanh", "qdbanhanh", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("SystudienEntity", "TenEng", "ten_eng", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("SystudienEntity", "TenFieldname", "ten_fieldname", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("SystudienEntity", "TenTudien", "ten_tudien", false, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("SystudienEntity", "TenVie", "ten_vie", true, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("SystudienEntity", "TrangThai", "trang_thai", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 13);
		}

		/// <summary>Inits SysunitEntity's mappings</summary>
		private void InitSysunitEntityMappings()
		{
			this.AddElementMapping("SysunitEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysunit", 27, 0);
			this.AddElementFieldMapping("SysunitEntity", "Capdonvi", "capdonvi", true, "Varchar", 20, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SysunitEntity", "Coquanbanhanhqd", "coquanbanhanhqd", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("SysunitEntity", "Diachi", "diachi", true, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 2);
			this.AddElementFieldMapping("SysunitEntity", "Dinhdanhapp", "dinhdanhapp", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysunitEntity", "Email", "email", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SysunitEntity", "Fax", "fax", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SysunitEntity", "IdDiaban", "id_diaban", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 6);
			this.AddElementFieldMapping("SysunitEntity", "IdHuyen", "id_huyen", true, "Varchar", 1, 0, 0, false, "", null, typeof(System.String), 7);
			this.AddElementFieldMapping("SysunitEntity", "IdTinh", "id_tinh", true, "Varchar", 1, 0, 0, false, "", null, typeof(System.String), 8);
			this.AddElementFieldMapping("SysunitEntity", "IdTochuc", "id_tochuc", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 9);
			this.AddElementFieldMapping("SysunitEntity", "IdXa", "id_xa", true, "Varchar", 1, 0, 0, false, "", null, typeof(System.String), 10);
			this.AddElementFieldMapping("SysunitEntity", "Loaiunit", "loaiunit", true, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 11);
			this.AddElementFieldMapping("SysunitEntity", "Macha", "macha", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("SysunitEntity", "Madinhdanh", "madinhdanh", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 13);
			this.AddElementFieldMapping("SysunitEntity", "Madvqhns", "madvqhns", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 14);
			this.AddElementFieldMapping("SysunitEntity", "Mahuyen", "mahuyen", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("SysunitEntity", "Matinh", "matinh", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 16);
			this.AddElementFieldMapping("SysunitEntity", "Maxa", "maxa", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 17);
			this.AddElementFieldMapping("SysunitEntity", "Ngaybanhanhqd", "ngaybanhanhqd", false, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 18);
			this.AddElementFieldMapping("SysunitEntity", "Nguoilienhe", "nguoilienhe", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 19);
			this.AddElementFieldMapping("SysunitEntity", "Qdbanhanhqdsuadoi", "qdbanhanhqdsuadoi", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 20);
			this.AddElementFieldMapping("SysunitEntity", "Sodienthoai", "sodienthoai", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 21);
			this.AddElementFieldMapping("SysunitEntity", "Tendonvi", "tendonvi", false, "Varchar", 250, 0, 0, false, "", null, typeof(System.String), 22);
			this.AddElementFieldMapping("SysunitEntity", "Type", "type", true, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 23);
			this.AddElementFieldMapping("SysunitEntity", "Trangthai", "trangthai", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 24);
			this.AddElementFieldMapping("SysunitEntity", "Unitcode", "unitcode", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 25);
			this.AddElementFieldMapping("SysunitEntity", "Website", "website", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 26);
		}

		/// <summary>Inits SysuserEntity's mappings</summary>
		private void InitSysuserEntityMappings()
		{
			this.AddElementMapping("SysuserEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysuser", 25, 0);
			this.AddElementFieldMapping("SysuserEntity", "Appid", "appid", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SysuserEntity", "Cap", "cap", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 1);
			this.AddElementFieldMapping("SysuserEntity", "Checkisyn", "checkisyn", true, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 2);
			this.AddElementFieldMapping("SysuserEntity", "Diachi", "diachi", true, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 3);
			this.AddElementFieldMapping("SysuserEntity", "Email", "email", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 4);
			this.AddElementFieldMapping("SysuserEntity", "Fullname", "fullname", false, "Varchar", 200, 0, 0, false, "", null, typeof(System.String), 5);
			this.AddElementFieldMapping("SysuserEntity", "Gioitinh", "gioitinh", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 6);
			this.AddElementFieldMapping("SysuserEntity", "IdChucvu", "id_chucvu", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 7);
			this.AddElementFieldMapping("SysuserEntity", "Idsystudien", "idsystudien", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 8);
			this.AddElementFieldMapping("SysuserEntity", "Imgavatar", "imgavatar", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 9);
			this.AddElementFieldMapping("SysuserEntity", "Loaiuser", "loaiuser", true, "Smallint", 0, 5, 0, false, "", null, typeof(System.Int16), 10);
			this.AddElementFieldMapping("SysuserEntity", "Machucvu", "machucvu", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 11);
			this.AddElementFieldMapping("SysuserEntity", "Madbhc", "madbhc", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 12);
			this.AddElementFieldMapping("SysuserEntity", "Msthue", "msthue", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 13);
			this.AddElementFieldMapping("SysuserEntity", "Ngaysinh", "ngaysinh", true, "Timestamp", 0, 0, 0, false, "", null, typeof(System.DateTime), 14);
			this.AddElementFieldMapping("SysuserEntity", "Nglienhe", "nglienhe", true, "Varchar", 150, 0, 0, false, "", null, typeof(System.String), 15);
			this.AddElementFieldMapping("SysuserEntity", "Password", "password", false, "Varchar", 500, 0, 0, false, "", null, typeof(System.String), 16);
			this.AddElementFieldMapping("SysuserEntity", "Phone", "phone", true, "Varchar", 11, 0, 0, false, "", null, typeof(System.String), 17);
			this.AddElementFieldMapping("SysuserEntity", "Phongban", "phongban", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 18);
			this.AddElementFieldMapping("SysuserEntity", "Quoctich", "quoctich", true, "Varchar", 100, 0, 0, false, "", null, typeof(System.String), 19);
			this.AddElementFieldMapping("SysuserEntity", "Socmnd", "socmnd", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 20);
			this.AddElementFieldMapping("SysuserEntity", "Trangthai", "trangthai", true, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 21);
			this.AddElementFieldMapping("SysuserEntity", "Unitcode", "unitcode", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 22);
			this.AddElementFieldMapping("SysuserEntity", "Userid", "userid", false, "Bigint", 0, 20, 0, true, "SystemIdentity", null, typeof(System.Int64), 23);
			this.AddElementFieldMapping("SysuserEntity", "Username", "username", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 24);
		}

		/// <summary>Inits SysusergroupEntity's mappings</summary>
		private void InitSysusergroupEntityMappings()
		{
			this.AddElementMapping("SysusergroupEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysusergroup", 2, 0);
			this.AddElementFieldMapping("SysusergroupEntity", "Groupid", "groupid", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("SysusergroupEntity", "Userid", "userid", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
		}

		/// <summary>Inits SysusermenuEntity's mappings</summary>
		private void InitSysusermenuEntityMappings()
		{
			this.AddElementMapping("SysusermenuEntity", @"DATAWAREHOUSEBG", @"appqtht", "sysusermenu", 3, 0);
			this.AddElementFieldMapping("SysusermenuEntity", "Function", "function", true, "Varchar", 50, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("SysusermenuEntity", "Menuid", "menuid", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
			this.AddElementFieldMapping("SysusermenuEntity", "Userid", "userid", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 2);
		}

		/// <summary>Inits TochucChucvuEntity's mappings</summary>
		private void InitTochucChucvuEntityMappings()
		{
			this.AddElementMapping("TochucChucvuEntity", @"DATAWAREHOUSEBG", @"appqtht", "tochuc_chucvu", 3, 0);
			this.AddElementFieldMapping("TochucChucvuEntity", "Cap", "cap", true, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("TochucChucvuEntity", "IdChucvu", "id_chucvu", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
			this.AddElementFieldMapping("TochucChucvuEntity", "IdTochuc", "id_tochuc", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 2);
		}

	}
}
