//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Syscauhinh'.<br/><br/></summary>
	[Serializable]
	public partial class SyscauhinhEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SyscauhinhEntityStaticMetaData _staticMetaData = new SyscauhinhEntityStaticMetaData();
		private static SyscauhinhRelations _relationsFactory = new SyscauhinhRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SyscauhinhEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SyscauhinhEntityStaticMetaData()
			{
				SetEntityCoreInfo("SyscauhinhEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SyscauhinhEntity, typeof(SyscauhinhEntity), typeof(SyscauhinhEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SyscauhinhEntity()
		{
		}

		/// <summary> CTor</summary>
		public SyscauhinhEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SyscauhinhEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SyscauhinhEntity</param>
		public SyscauhinhEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Syscauhinh which data should be fetched into this Syscauhinh object</param>
		public SyscauhinhEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Syscauhinh which data should be fetched into this Syscauhinh object</param>
		/// <param name="validator">The custom validator object for this SyscauhinhEntity</param>
		public SyscauhinhEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SyscauhinhEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SyscauhinhEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SyscauhinhRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Doanduongden property of the Entity Syscauhinh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscauhinh"."doanduongden".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Doanduongden
		{
			get { return (System.String)GetValue((int)SyscauhinhFieldIndex.Doanduongden, true); }
			set	{ SetValue((int)SyscauhinhFieldIndex.Doanduongden, value); }
		}

		/// <summary>The Doanduongtu property of the Entity Syscauhinh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscauhinh"."doanduongtu".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Doanduongtu
		{
			get { return (System.String)GetValue((int)SyscauhinhFieldIndex.Doanduongtu, true); }
			set	{ SetValue((int)SyscauhinhFieldIndex.Doanduongtu, value); }
		}

		/// <summary>The Endtime property of the Entity Syscauhinh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscauhinh"."endtime".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Endtime
		{
			get { return (System.String)GetValue((int)SyscauhinhFieldIndex.Endtime, true); }
			set	{ SetValue((int)SyscauhinhFieldIndex.Endtime, value); }
		}

		/// <summary>The Id property of the Entity Syscauhinh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscauhinh"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SyscauhinhFieldIndex.Id, true); }
			set { SetValue((int)SyscauhinhFieldIndex.Id, value); }		}

		/// <summary>The Starttime property of the Entity Syscauhinh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscauhinh"."starttime".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Starttime
		{
			get { return (System.String)GetValue((int)SyscauhinhFieldIndex.Starttime, true); }
			set	{ SetValue((int)SyscauhinhFieldIndex.Starttime, value); }
		}

		/// <summary>The Status property of the Entity Syscauhinh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscauhinh"."status".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Status
		{
			get { return (Nullable<System.Int32>)GetValue((int)SyscauhinhFieldIndex.Status, false); }
			set	{ SetValue((int)SyscauhinhFieldIndex.Status, value); }
		}

		/// <summary>The Tansuat property of the Entity Syscauhinh<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscauhinh"."tansuat".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Tansuat
		{
			get { return (System.String)GetValue((int)SyscauhinhFieldIndex.Tansuat, true); }
			set	{ SetValue((int)SyscauhinhFieldIndex.Tansuat, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SyscauhinhFieldIndex
	{
		///<summary>Doanduongden. </summary>
		Doanduongden,
		///<summary>Doanduongtu. </summary>
		Doanduongtu,
		///<summary>Endtime. </summary>
		Endtime,
		///<summary>Id. </summary>
		Id,
		///<summary>Starttime. </summary>
		Starttime,
		///<summary>Status. </summary>
		Status,
		///<summary>Tansuat. </summary>
		Tansuat,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Syscauhinh. </summary>
	public partial class SyscauhinhRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSyscauhinhRelations
	{

		/// <summary>CTor</summary>
		static StaticSyscauhinhRelations() { }
	}
}
