//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Syscsgt'.<br/><br/></summary>
	[Serializable]
	public partial class SyscsgtEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SyscsgtEntityStaticMetaData _staticMetaData = new SyscsgtEntityStaticMetaData();
		private static SyscsgtRelations _relationsFactory = new SyscsgtRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SyscsgtEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SyscsgtEntityStaticMetaData()
			{
				SetEntityCoreInfo("SyscsgtEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SyscsgtEntity, typeof(SyscsgtEntity), typeof(SyscsgtEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SyscsgtEntity()
		{
		}

		/// <summary> CTor</summary>
		public SyscsgtEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SyscsgtEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SyscsgtEntity</param>
		public SyscsgtEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Syscsgt which data should be fetched into this Syscsgt object</param>
		public SyscsgtEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Syscsgt which data should be fetched into this Syscsgt object</param>
		/// <param name="validator">The custom validator object for this SyscsgtEntity</param>
		public SyscsgtEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SyscsgtEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SyscsgtEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SyscsgtRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Createddate property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."createddate".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Createddate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SyscsgtFieldIndex.Createddate, false); }
			set	{ SetValue((int)SyscsgtFieldIndex.Createddate, value); }
		}

		/// <summary>The Chucvu property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."chucvu".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Chucvu
		{
			get { return (Nullable<System.Int32>)GetValue((int)SyscsgtFieldIndex.Chucvu, false); }
			set	{ SetValue((int)SyscsgtFieldIndex.Chucvu, value); }
		}

		/// <summary>The Diachi property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."diachi".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Diachi
		{
			get { return (System.String)GetValue((int)SyscsgtFieldIndex.Diachi, true); }
			set	{ SetValue((int)SyscsgtFieldIndex.Diachi, value); }
		}

		/// <summary>The Donvi property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."donvi".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Donvi
		{
			get { return (System.String)GetValue((int)SyscsgtFieldIndex.Donvi, true); }
			set	{ SetValue((int)SyscsgtFieldIndex.Donvi, value); }
		}

		/// <summary>The Ghichu property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."ghichu".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Ghichu
		{
			get { return (System.String)GetValue((int)SyscsgtFieldIndex.Ghichu, true); }
			set	{ SetValue((int)SyscsgtFieldIndex.Ghichu, value); }
		}

		/// <summary>The Hovaten property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."hovaten".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Hovaten
		{
			get { return (System.String)GetValue((int)SyscsgtFieldIndex.Hovaten, true); }
			set	{ SetValue((int)SyscsgtFieldIndex.Hovaten, value); }
		}

		/// <summary>The Id property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SyscsgtFieldIndex.Id, true); }
			set { SetValue((int)SyscsgtFieldIndex.Id, value); }		}

		/// <summary>The Mahuyen property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."mahuyen".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Mahuyen
		{
			get { return (System.String)GetValue((int)SyscsgtFieldIndex.Mahuyen, true); }
			set	{ SetValue((int)SyscsgtFieldIndex.Mahuyen, value); }
		}

		/// <summary>The Maxa property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."maxa".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Maxa
		{
			get { return (System.String)GetValue((int)SyscsgtFieldIndex.Maxa, true); }
			set	{ SetValue((int)SyscsgtFieldIndex.Maxa, value); }
		}

		/// <summary>The Shape property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."shape".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Shape
		{
			get { return (System.String)GetValue((int)SyscsgtFieldIndex.Shape, true); }
			set	{ SetValue((int)SyscsgtFieldIndex.Shape, value); }
		}

		/// <summary>The Sodienthoai property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."sodienthoai".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Sodienthoai
		{
			get { return (System.String)GetValue((int)SyscsgtFieldIndex.Sodienthoai, true); }
			set	{ SetValue((int)SyscsgtFieldIndex.Sodienthoai, value); }
		}

		/// <summary>The Status property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."status".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Status
		{
			get { return (Nullable<System.Int32>)GetValue((int)SyscsgtFieldIndex.Status, false); }
			set	{ SetValue((int)SyscsgtFieldIndex.Status, value); }
		}

		/// <summary>The Userid property of the Entity Syscsgt<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syscsgt"."userid".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Userid
		{
			get { return (Nullable<System.Int32>)GetValue((int)SyscsgtFieldIndex.Userid, false); }
			set	{ SetValue((int)SyscsgtFieldIndex.Userid, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SyscsgtFieldIndex
	{
		///<summary>Createddate. </summary>
		Createddate,
		///<summary>Chucvu. </summary>
		Chucvu,
		///<summary>Diachi. </summary>
		Diachi,
		///<summary>Donvi. </summary>
		Donvi,
		///<summary>Ghichu. </summary>
		Ghichu,
		///<summary>Hovaten. </summary>
		Hovaten,
		///<summary>Id. </summary>
		Id,
		///<summary>Mahuyen. </summary>
		Mahuyen,
		///<summary>Maxa. </summary>
		Maxa,
		///<summary>Shape. </summary>
		Shape,
		///<summary>Sodienthoai. </summary>
		Sodienthoai,
		///<summary>Status. </summary>
		Status,
		///<summary>Userid. </summary>
		Userid,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Syscsgt. </summary>
	public partial class SyscsgtRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSyscsgtRelations
	{

		/// <summary>CTor</summary>
		static StaticSyscsgtRelations() { }
	}
}
