//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Sysdmtrangthietbipccc'.<br/><br/></summary>
	[Serializable]
	public partial class SysdmtrangthietbipcccEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysdmtrangthietbipcccEntityStaticMetaData _staticMetaData = new SysdmtrangthietbipcccEntityStaticMetaData();
		private static SysdmtrangthietbipcccRelations _relationsFactory = new SysdmtrangthietbipcccRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysdmtrangthietbipcccEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysdmtrangthietbipcccEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysdmtrangthietbipcccEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SysdmtrangthietbipcccEntity, typeof(SysdmtrangthietbipcccEntity), typeof(SysdmtrangthietbipcccEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SysdmtrangthietbipcccEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysdmtrangthietbipcccEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysdmtrangthietbipcccEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysdmtrangthietbipcccEntity</param>
		public SysdmtrangthietbipcccEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysdmtrangthietbipccc which data should be fetched into this Sysdmtrangthietbipccc object</param>
		public SysdmtrangthietbipcccEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysdmtrangthietbipccc which data should be fetched into this Sysdmtrangthietbipccc object</param>
		/// <param name="validator">The custom validator object for this SysdmtrangthietbipcccEntity</param>
		public SysdmtrangthietbipcccEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysdmtrangthietbipcccEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysdmtrangthietbipcccEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysdmtrangthietbipcccRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Id property of the Entity Sysdmtrangthietbipccc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdmtrangthietbipccc"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SysdmtrangthietbipcccFieldIndex.Id, true); }
			set { SetValue((int)SysdmtrangthietbipcccFieldIndex.Id, value); }		}

		/// <summary>The Loaithietbi property of the Entity Sysdmtrangthietbipccc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdmtrangthietbipccc"."loaithietbi".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Loaithietbi
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysdmtrangthietbipcccFieldIndex.Loaithietbi, false); }
			set	{ SetValue((int)SysdmtrangthietbipcccFieldIndex.Loaithietbi, value); }
		}

		/// <summary>The Macha property of the Entity Sysdmtrangthietbipccc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdmtrangthietbipccc"."macha".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Macha
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysdmtrangthietbipcccFieldIndex.Macha, false); }
			set	{ SetValue((int)SysdmtrangthietbipcccFieldIndex.Macha, value); }
		}

		/// <summary>The Mota property of the Entity Sysdmtrangthietbipccc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdmtrangthietbipccc"."mota".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Mota
		{
			get { return (System.String)GetValue((int)SysdmtrangthietbipcccFieldIndex.Mota, true); }
			set	{ SetValue((int)SysdmtrangthietbipcccFieldIndex.Mota, value); }
		}

		/// <summary>The Tenthietbi property of the Entity Sysdmtrangthietbipccc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdmtrangthietbipccc"."tenthietbi".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Tenthietbi
		{
			get { return (System.String)GetValue((int)SysdmtrangthietbipcccFieldIndex.Tenthietbi, true); }
			set	{ SetValue((int)SysdmtrangthietbipcccFieldIndex.Tenthietbi, value); }
		}

		/// <summary>The Trangthai property of the Entity Sysdmtrangthietbipccc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysdmtrangthietbipccc"."trangthai".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Trangthai
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysdmtrangthietbipcccFieldIndex.Trangthai, false); }
			set	{ SetValue((int)SysdmtrangthietbipcccFieldIndex.Trangthai, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SysdmtrangthietbipcccFieldIndex
	{
		///<summary>Id. </summary>
		Id,
		///<summary>Loaithietbi. </summary>
		Loaithietbi,
		///<summary>Macha. </summary>
		Macha,
		///<summary>Mota. </summary>
		Mota,
		///<summary>Tenthietbi. </summary>
		Tenthietbi,
		///<summary>Trangthai. </summary>
		Trangthai,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Sysdmtrangthietbipccc. </summary>
	public partial class SysdmtrangthietbipcccRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysdmtrangthietbipcccRelations
	{

		/// <summary>CTor</summary>
		static StaticSysdmtrangthietbipcccRelations() { }
	}
}
