//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'SysfeatureclassUser'.<br/><br/></summary>
	[Serializable]
	public partial class SysfeatureclassUserEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysfeatureclassUserEntityStaticMetaData _staticMetaData = new SysfeatureclassUserEntityStaticMetaData();
		private static SysfeatureclassUserRelations _relationsFactory = new SysfeatureclassUserRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysfeatureclassUserEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysfeatureclassUserEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysfeatureclassUserEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SysfeatureclassUserEntity, typeof(SysfeatureclassUserEntity), typeof(SysfeatureclassUserEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SysfeatureclassUserEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysfeatureclassUserEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysfeatureclassUserEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysfeatureclassUserEntity</param>
		public SysfeatureclassUserEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for SysfeatureclassUser which data should be fetched into this SysfeatureclassUser object</param>
		public SysfeatureclassUserEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for SysfeatureclassUser which data should be fetched into this SysfeatureclassUser object</param>
		/// <param name="validator">The custom validator object for this SysfeatureclassUserEntity</param>
		public SysfeatureclassUserEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysfeatureclassUserEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysfeatureclassUserEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysfeatureclassUserRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Config property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."config".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Config
		{
			get { return (System.String)GetValue((int)SysfeatureclassUserFieldIndex.Config, true); }
			set	{ SetValue((int)SysfeatureclassUserFieldIndex.Config, value); }
		}

		/// <summary>The Datecreated property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."datecreated".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Datecreated
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SysfeatureclassUserFieldIndex.Datecreated, false); }
			set	{ SetValue((int)SysfeatureclassUserFieldIndex.Datecreated, value); }
		}

		/// <summary>The Datemodified property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."datemodified".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Datemodified
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SysfeatureclassUserFieldIndex.Datemodified, false); }
			set	{ SetValue((int)SysfeatureclassUserFieldIndex.Datemodified, value); }
		}

		/// <summary>The Featureclassid property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."featureclassid".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Featureclassid
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysfeatureclassUserFieldIndex.Featureclassid, false); }
			set	{ SetValue((int)SysfeatureclassUserFieldIndex.Featureclassid, value); }
		}

		/// <summary>The Groupid property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."groupid".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Groupid
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysfeatureclassUserFieldIndex.Groupid, false); }
			set	{ SetValue((int)SysfeatureclassUserFieldIndex.Groupid, value); }
		}

		/// <summary>The Id property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SysfeatureclassUserFieldIndex.Id, true); }
			set { SetValue((int)SysfeatureclassUserFieldIndex.Id, value); }		}

		/// <summary>The Permission property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."permission".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Permission
		{
			get { return (System.String)GetValue((int)SysfeatureclassUserFieldIndex.Permission, true); }
			set	{ SetValue((int)SysfeatureclassUserFieldIndex.Permission, value); }
		}

		/// <summary>The Usercreated property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."usercreated".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Usercreated
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysfeatureclassUserFieldIndex.Usercreated, false); }
			set	{ SetValue((int)SysfeatureclassUserFieldIndex.Usercreated, value); }
		}

		/// <summary>The Username property of the Entity SysfeatureclassUser<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfeatureclass_user"."username".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Username
		{
			get { return (System.String)GetValue((int)SysfeatureclassUserFieldIndex.Username, true); }
			set	{ SetValue((int)SysfeatureclassUserFieldIndex.Username, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SysfeatureclassUserFieldIndex
	{
		///<summary>Config. </summary>
		Config,
		///<summary>Datecreated. </summary>
		Datecreated,
		///<summary>Datemodified. </summary>
		Datemodified,
		///<summary>Featureclassid. </summary>
		Featureclassid,
		///<summary>Groupid. </summary>
		Groupid,
		///<summary>Id. </summary>
		Id,
		///<summary>Permission. </summary>
		Permission,
		///<summary>Usercreated. </summary>
		Usercreated,
		///<summary>Username. </summary>
		Username,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: SysfeatureclassUser. </summary>
	public partial class SysfeatureclassUserRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysfeatureclassUserRelations
	{

		/// <summary>CTor</summary>
		static StaticSysfeatureclassUserRelations() { }
	}
}
