//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Sysfile'.<br/><br/></summary>
	[Serializable]
	public partial class SysfileEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysfileEntityStaticMetaData _staticMetaData = new SysfileEntityStaticMetaData();
		private static SysfileRelations _relationsFactory = new SysfileRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysfileEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysfileEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysfileEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SysfileEntity, typeof(SysfileEntity), typeof(SysfileEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SysfileEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysfileEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysfileEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysfileEntity</param>
		public SysfileEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysfile which data should be fetched into this Sysfile object</param>
		public SysfileEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysfile which data should be fetched into this Sysfile object</param>
		/// <param name="validator">The custom validator object for this SysfileEntity</param>
		public SysfileEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysfileEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysfileEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysfileRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Createby property of the Entity Sysfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfile"."createby".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Createby
		{
			get { return (System.String)GetValue((int)SysfileFieldIndex.Createby, true); }
			set	{ SetValue((int)SysfileFieldIndex.Createby, value); }
		}

		/// <summary>The Folder property of the Entity Sysfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfile"."folder".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Folder
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysfileFieldIndex.Folder, false); }
			set	{ SetValue((int)SysfileFieldIndex.Folder, value); }
		}

		/// <summary>The Id property of the Entity Sysfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfile"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SysfileFieldIndex.Id, true); }
			set { SetValue((int)SysfileFieldIndex.Id, value); }		}

		/// <summary>The Length property of the Entity Sysfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfile"."length".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Length
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysfileFieldIndex.Length, false); }
			set	{ SetValue((int)SysfileFieldIndex.Length, value); }
		}

		/// <summary>The Name property of the Entity Sysfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfile"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)SysfileFieldIndex.Name, true); }
			set	{ SetValue((int)SysfileFieldIndex.Name, value); }
		}

		/// <summary>The Path property of the Entity Sysfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfile"."path".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Path
		{
			get { return (System.String)GetValue((int)SysfileFieldIndex.Path, true); }
			set	{ SetValue((int)SysfileFieldIndex.Path, value); }
		}

		/// <summary>The Type property of the Entity Sysfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfile"."type".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Type
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysfileFieldIndex.Type, false); }
			set	{ SetValue((int)SysfileFieldIndex.Type, value); }
		}

		/// <summary>The Unitcode property of the Entity Sysfile<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysfile"."unitcode".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Unitcode
		{
			get { return (System.String)GetValue((int)SysfileFieldIndex.Unitcode, true); }
			set	{ SetValue((int)SysfileFieldIndex.Unitcode, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SysfileFieldIndex
	{
		///<summary>Createby. </summary>
		Createby,
		///<summary>Folder. </summary>
		Folder,
		///<summary>Id. </summary>
		Id,
		///<summary>Length. </summary>
		Length,
		///<summary>Name. </summary>
		Name,
		///<summary>Path. </summary>
		Path,
		///<summary>Type. </summary>
		Type,
		///<summary>Unitcode. </summary>
		Unitcode,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Sysfile. </summary>
	public partial class SysfileRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysfileRelations
	{

		/// <summary>CTor</summary>
		static StaticSysfileRelations() { }
	}
}
