//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Syshistoryuserline'.<br/><br/></summary>
	[Serializable]
	public partial class SyshistoryuserlineEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SyshistoryuserlineEntityStaticMetaData _staticMetaData = new SyshistoryuserlineEntityStaticMetaData();
		private static SyshistoryuserlineRelations _relationsFactory = new SyshistoryuserlineRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SyshistoryuserlineEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SyshistoryuserlineEntityStaticMetaData()
			{
				SetEntityCoreInfo("SyshistoryuserlineEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SyshistoryuserlineEntity, typeof(SyshistoryuserlineEntity), typeof(SyshistoryuserlineEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SyshistoryuserlineEntity()
		{
		}

		/// <summary> CTor</summary>
		public SyshistoryuserlineEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SyshistoryuserlineEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SyshistoryuserlineEntity</param>
		public SyshistoryuserlineEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Syshistoryuserline which data should be fetched into this Syshistoryuserline object</param>
		public SyshistoryuserlineEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Syshistoryuserline which data should be fetched into this Syshistoryuserline object</param>
		/// <param name="validator">The custom validator object for this SyshistoryuserlineEntity</param>
		public SyshistoryuserlineEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SyshistoryuserlineEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SyshistoryuserlineEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SyshistoryuserlineRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Createddate property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."createddate".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Createddate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SyshistoryuserlineFieldIndex.Createddate, false); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Createddate, value); }
		}

		/// <summary>The Device property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."device".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Device
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Device, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Device, value); }
		}

		/// <summary>The Deviceinfo property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."deviceinfo".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Deviceinfo
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Deviceinfo, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Deviceinfo, value); }
		}

		/// <summary>The Dieukien property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."dieukien".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Dieukien
		{
			get { return (Nullable<System.Int32>)GetValue((int)SyshistoryuserlineFieldIndex.Dieukien, false); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Dieukien, value); }
		}

		/// <summary>The Icon property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."icon".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10485760.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Icon
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Icon, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Icon, value); }
		}

		/// <summary>The Id property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SyshistoryuserlineFieldIndex.Id, true); }
			set { SetValue((int)SyshistoryuserlineFieldIndex.Id, value); }		}

		/// <summary>The Mahuyen property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."mahuyen".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Mahuyen
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Mahuyen, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Mahuyen, value); }
		}

		/// <summary>The Maxa property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."maxa".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Maxa
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Maxa, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Maxa, value); }
		}

		/// <summary>The Shape property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."shape".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Shape
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Shape, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Shape, value); }
		}

		/// <summary>The Status property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."status".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Status
		{
			get { return (Nullable<System.Int32>)GetValue((int)SyshistoryuserlineFieldIndex.Status, false); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Status, value); }
		}

		/// <summary>The Typedata property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."typedata".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Typedata
		{
			get { return (Nullable<System.Int32>)GetValue((int)SyshistoryuserlineFieldIndex.Typedata, false); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Typedata, value); }
		}

		/// <summary>The Unitcode property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."unitcode".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Unitcode
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Unitcode, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Unitcode, value); }
		}

		/// <summary>The Userid property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."userid".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Userid
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Userid, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Userid, value); }
		}

		/// <summary>The Username property of the Entity Syshistoryuserline<br/><br/></summary>
		/// <remarks>Mapped on  table field: "syshistoryuserline"."username".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Username
		{
			get { return (System.String)GetValue((int)SyshistoryuserlineFieldIndex.Username, true); }
			set	{ SetValue((int)SyshistoryuserlineFieldIndex.Username, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SyshistoryuserlineFieldIndex
	{
		///<summary>Createddate. </summary>
		Createddate,
		///<summary>Device. </summary>
		Device,
		///<summary>Deviceinfo. </summary>
		Deviceinfo,
		///<summary>Dieukien. </summary>
		Dieukien,
		///<summary>Icon. </summary>
		Icon,
		///<summary>Id. </summary>
		Id,
		///<summary>Mahuyen. </summary>
		Mahuyen,
		///<summary>Maxa. </summary>
		Maxa,
		///<summary>Shape. </summary>
		Shape,
		///<summary>Status. </summary>
		Status,
		///<summary>Typedata. </summary>
		Typedata,
		///<summary>Unitcode. </summary>
		Unitcode,
		///<summary>Userid. </summary>
		Userid,
		///<summary>Username. </summary>
		Username,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Syshistoryuserline. </summary>
	public partial class SyshistoryuserlineRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSyshistoryuserlineRelations
	{

		/// <summary>CTor</summary>
		static StaticSyshistoryuserlineRelations() { }
	}
}
