//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Sysphuongand'.<br/><br/></summary>
	[Serializable]
	public partial class SysphuongandEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysphuongandEntityStaticMetaData _staticMetaData = new SysphuongandEntityStaticMetaData();
		private static SysphuongandRelations _relationsFactory = new SysphuongandRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysphuongandEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysphuongandEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysphuongandEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SysphuongandEntity, typeof(SysphuongandEntity), typeof(SysphuongandEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SysphuongandEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysphuongandEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysphuongandEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysphuongandEntity</param>
		public SysphuongandEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysphuongand which data should be fetched into this Sysphuongand object</param>
		public SysphuongandEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysphuongand which data should be fetched into this Sysphuongand object</param>
		/// <param name="validator">The custom validator object for this SysphuongandEntity</param>
		public SysphuongandEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysphuongandEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysphuongandEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysphuongandRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Createdate property of the Entity Sysphuongand<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuongand"."createdate".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Createdate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SysphuongandFieldIndex.Createdate, false); }
			set	{ SetValue((int)SysphuongandFieldIndex.Createdate, value); }
		}

		/// <summary>The Danhgia property of the Entity Sysphuongand<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuongand"."danhgia".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Danhgia
		{
			get { return (System.String)GetValue((int)SysphuongandFieldIndex.Danhgia, true); }
			set	{ SetValue((int)SysphuongandFieldIndex.Danhgia, value); }
		}

		/// <summary>The Id property of the Entity Sysphuongand<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuongand"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SysphuongandFieldIndex.Id, true); }
			set { SetValue((int)SysphuongandFieldIndex.Id, value); }		}

		/// <summary>The Idttphieu property of the Entity Sysphuongand<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuongand"."idttphieu".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Idttphieu
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysphuongandFieldIndex.Idttphieu, false); }
			set	{ SetValue((int)SysphuongandFieldIndex.Idttphieu, value); }
		}

		/// <summary>The Lucluongthgia property of the Entity Sysphuongand<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuongand"."lucluongthgia".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Lucluongthgia
		{
			get { return (System.String)GetValue((int)SysphuongandFieldIndex.Lucluongthgia, true); }
			set	{ SetValue((int)SysphuongandFieldIndex.Lucluongthgia, value); }
		}

		/// <summary>The Ndhoctap property of the Entity Sysphuongand<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuongand"."ndhoctap".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Ndhoctap
		{
			get { return (System.String)GetValue((int)SysphuongandFieldIndex.Ndhoctap, true); }
			set	{ SetValue((int)SysphuongandFieldIndex.Ndhoctap, value); }
		}

		/// <summary>The Thchay property of the Entity Sysphuongand<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuongand"."thchay".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Thchay
		{
			get { return (System.String)GetValue((int)SysphuongandFieldIndex.Thchay, true); }
			set	{ SetValue((int)SysphuongandFieldIndex.Thchay, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SysphuongandFieldIndex
	{
		///<summary>Createdate. </summary>
		Createdate,
		///<summary>Danhgia. </summary>
		Danhgia,
		///<summary>Id. </summary>
		Id,
		///<summary>Idttphieu. </summary>
		Idttphieu,
		///<summary>Lucluongthgia. </summary>
		Lucluongthgia,
		///<summary>Ndhoctap. </summary>
		Ndhoctap,
		///<summary>Thchay. </summary>
		Thchay,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Sysphuongand. </summary>
	public partial class SysphuongandRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysphuongandRelations
	{

		/// <summary>CTor</summary>
		static StaticSysphuongandRelations() { }
	}
}
