//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Sysphuonganc'.<br/><br/></summary>
	[Serializable]
	public partial class SysphuongancEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysphuongancEntityStaticMetaData _staticMetaData = new SysphuongancEntityStaticMetaData();
		private static SysphuongancRelations _relationsFactory = new SysphuongancRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysphuongancEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysphuongancEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysphuongancEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SysphuongancEntity, typeof(SysphuongancEntity), typeof(SysphuongancEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SysphuongancEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysphuongancEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysphuongancEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysphuongancEntity</param>
		public SysphuongancEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysphuonganc which data should be fetched into this Sysphuonganc object</param>
		public SysphuongancEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysphuonganc which data should be fetched into this Sysphuonganc object</param>
		/// <param name="validator">The custom validator object for this SysphuongancEntity</param>
		public SysphuongancEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysphuongancEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysphuongancEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysphuongancRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Createdate property of the Entity Sysphuonganc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuonganc"."createdate".<br/>Table field type characteristics (type, precision, scale, length): Date, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Createdate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)SysphuongancFieldIndex.Createdate, false); }
			set	{ SetValue((int)SysphuongancFieldIndex.Createdate, value); }
		}

		/// <summary>The Id property of the Entity Sysphuonganc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuonganc"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SysphuongancFieldIndex.Id, true); }
			set { SetValue((int)SysphuongancFieldIndex.Id, value); }		}

		/// <summary>The Idttphieu property of the Entity Sysphuonganc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuonganc"."idttphieu".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Idttphieu
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysphuongancFieldIndex.Idttphieu, false); }
			set	{ SetValue((int)SysphuongancFieldIndex.Idttphieu, value); }
		}

		/// <summary>The Ndbosung property of the Entity Sysphuonganc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuonganc"."ndbosung".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Ndbosung
		{
			get { return (System.String)GetValue((int)SysphuongancFieldIndex.Ndbosung, true); }
			set	{ SetValue((int)SysphuongancFieldIndex.Ndbosung, value); }
		}

		/// <summary>The Nguoiduyet property of the Entity Sysphuonganc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuonganc"."nguoiduyet".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Nguoiduyet
		{
			get { return (System.String)GetValue((int)SysphuongancFieldIndex.Nguoiduyet, true); }
			set	{ SetValue((int)SysphuongancFieldIndex.Nguoiduyet, value); }
		}

		/// <summary>The Nguoixaydung property of the Entity Sysphuonganc<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysphuonganc"."nguoixaydung".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Nguoixaydung
		{
			get { return (System.String)GetValue((int)SysphuongancFieldIndex.Nguoixaydung, true); }
			set	{ SetValue((int)SysphuongancFieldIndex.Nguoixaydung, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SysphuongancFieldIndex
	{
		///<summary>Createdate. </summary>
		Createdate,
		///<summary>Id. </summary>
		Id,
		///<summary>Idttphieu. </summary>
		Idttphieu,
		///<summary>Ndbosung. </summary>
		Ndbosung,
		///<summary>Nguoiduyet. </summary>
		Nguoiduyet,
		///<summary>Nguoixaydung. </summary>
		Nguoixaydung,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Sysphuonganc. </summary>
	public partial class SysphuongancRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysphuongancRelations
	{

		/// <summary>CTor</summary>
		static StaticSysphuongancRelations() { }
	}
}
