//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.CongAnGis.Dal.HelperClasses;
using App.CongAnGis.Dal.FactoryClasses;
using App.CongAnGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.CongAnGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Sysuserhistory'.<br/><br/></summary>
	[Serializable]
	public partial class SysuserhistoryEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysuserhistoryEntityStaticMetaData _staticMetaData = new SysuserhistoryEntityStaticMetaData();
		private static SysuserhistoryRelations _relationsFactory = new SysuserhistoryRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysuserhistoryEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysuserhistoryEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysuserhistoryEntity", InheritanceHierarchyType.None, false, (int)App.CongAnGis.Dal.EntityType.SysuserhistoryEntity, typeof(SysuserhistoryEntity), typeof(SysuserhistoryEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static SysuserhistoryEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysuserhistoryEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysuserhistoryEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysuserhistoryEntity</param>
		public SysuserhistoryEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysuserhistory which data should be fetched into this Sysuserhistory object</param>
		public SysuserhistoryEntity(System.Int32 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Sysuserhistory which data should be fetched into this Sysuserhistory object</param>
		/// <param name="validator">The custom validator object for this SysuserhistoryEntity</param>
		public SysuserhistoryEntity(System.Int32 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysuserhistoryEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysuserhistoryEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysuserhistoryRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Createdate property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."createdate".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Createdate
		{
			get { return (System.String)GetValue((int)SysuserhistoryFieldIndex.Createdate, true); }
			set	{ SetValue((int)SysuserhistoryFieldIndex.Createdate, value); }
		}

		/// <summary>The Deviceinfo property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."deviceinfo".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Deviceinfo
		{
			get { return (System.String)GetValue((int)SysuserhistoryFieldIndex.Deviceinfo, true); }
			set	{ SetValue((int)SysuserhistoryFieldIndex.Deviceinfo, value); }
		}

		/// <summary>The Icon property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."icon".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Icon
		{
			get { return (System.String)GetValue((int)SysuserhistoryFieldIndex.Icon, true); }
			set	{ SetValue((int)SysuserhistoryFieldIndex.Icon, value); }
		}

		/// <summary>The Id property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."id".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int32 Id
		{
			get { return (System.Int32)GetValue((int)SysuserhistoryFieldIndex.Id, true); }
			set { SetValue((int)SysuserhistoryFieldIndex.Id, value); }		}

		/// <summary>The Model property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."model".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Model
		{
			get { return (System.String)GetValue((int)SysuserhistoryFieldIndex.Model, true); }
			set	{ SetValue((int)SysuserhistoryFieldIndex.Model, value); }
		}

		/// <summary>The Shape property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."shape".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Shape
		{
			get { return (System.String)GetValue((int)SysuserhistoryFieldIndex.Shape, true); }
			set	{ SetValue((int)SysuserhistoryFieldIndex.Shape, value); }
		}

		/// <summary>The Status property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."status".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Status
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysuserhistoryFieldIndex.Status, false); }
			set	{ SetValue((int)SysuserhistoryFieldIndex.Status, value); }
		}

		/// <summary>The Userid property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."userid".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> Userid
		{
			get { return (Nullable<System.Int32>)GetValue((int)SysuserhistoryFieldIndex.Userid, false); }
			set	{ SetValue((int)SysuserhistoryFieldIndex.Userid, value); }
		}

		/// <summary>The Username property of the Entity Sysuserhistory<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysuserhistory"."username".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Username
		{
			get { return (System.String)GetValue((int)SysuserhistoryFieldIndex.Username, true); }
			set	{ SetValue((int)SysuserhistoryFieldIndex.Username, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.CongAnGis.Dal
{
	public enum SysuserhistoryFieldIndex
	{
		///<summary>Createdate. </summary>
		Createdate,
		///<summary>Deviceinfo. </summary>
		Deviceinfo,
		///<summary>Icon. </summary>
		Icon,
		///<summary>Id. </summary>
		Id,
		///<summary>Model. </summary>
		Model,
		///<summary>Shape. </summary>
		Shape,
		///<summary>Status. </summary>
		Status,
		///<summary>Userid. </summary>
		Userid,
		///<summary>Username. </summary>
		Username,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.CongAnGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Sysuserhistory. </summary>
	public partial class SysuserhistoryRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysuserhistoryRelations
	{

		/// <summary>CTor</summary>
		static StaticSysuserhistoryRelations() { }
	}
}
