//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.8.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using Authorize.Dal.EntityClasses;
using Authorize.Dal.HelperClasses;
using Authorize.Dal.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Authorize.Dal.FactoryClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>general base class for the generated factories</summary>
	[Serializable]
	public partial class EntityFactoryBase2<TEntity> : EntityFactoryCore2
		where TEntity : EntityBase2, IEntity2
	{
		private readonly Authorize.Dal.EntityType _typeOfEntity;
		private readonly bool _isInHierarchy;

		/// <summary>CTor</summary>
		/// <param name="entityName">Name of the entity.</param>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <param name="isInHierarchy">If true, the entity of this factory is in an inheritance hierarchy, false otherwise</param>
		public EntityFactoryBase2(string entityName, Authorize.Dal.EntityType typeOfEntity, bool isInHierarchy) : base(entityName)
		{
			_typeOfEntity = typeOfEntity;
			_isInHierarchy = isInHierarchy;
		}
		
		/// <inheritdoc/>
		public override IEntityFields2 CreateFields() { return ModelInfoProviderSingleton.GetInstance().GetEntityFields(this.ForEntityName); }
		
		/// <inheritdoc/>
		public override IEntity2 CreateEntityFromEntityTypeValue(int entityTypeValue) {	return GeneralEntityFactory.Create((Authorize.Dal.EntityType)entityTypeValue); }

		/// <inheritdoc/>
		public override IRelationCollection CreateHierarchyRelations(string objectAlias) { return ModelInfoProviderSingleton.GetInstance().GetHierarchyRelations(this.ForEntityName, objectAlias); }

		/// <inheritdoc/>
		public override IEntityFactory2 GetEntityFactory(object[] fieldValues, Dictionary<string, int> entityFieldStartIndexesPerEntity) 
		{
			return (IEntityFactory2)ModelInfoProviderSingleton.GetInstance().GetEntityFactory(this.ForEntityName, fieldValues, entityFieldStartIndexesPerEntity) ?? this;
		}
		
		/// <inheritdoc/>
		public override IPredicateExpression GetEntityTypeFilter(bool negate, string objectAlias) {	return ModelInfoProviderSingleton.GetInstance().GetEntityTypeFilter(this.ForEntityName, objectAlias, negate);	}
						
		/// <inheritdoc/>
		public override IEntityCollection2 CreateEntityCollection()	{ return new EntityCollection<TEntity>(this); }
		
		/// <inheritdoc/>
		public override IEntityFields2 CreateHierarchyFields() 
		{
			return _isInHierarchy ? new EntityFields2(ModelInfoProviderSingleton.GetInstance().GetHierarchyFields(this.ForEntityName), ModelInfoProviderSingleton.GetInstance(), null) : base.CreateHierarchyFields();
		}
		
		/// <inheritdoc/>
		protected override Type ForEntityType { get { return typeof(TEntity); } }
	}

	/// <summary>Factory to create new, empty DangkychiaseEntity objects.</summary>
	[Serializable]
	public partial class DangkychiaseEntityFactory : EntityFactoryBase2<DangkychiaseEntity> 
	{
		/// <summary>CTor</summary>
		public DangkychiaseEntityFactory() : base("DangkychiaseEntity", Authorize.Dal.EntityType.DangkychiaseEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new DangkychiaseEntity(fields); }
	}

	/// <summary>Factory to create new, empty DmchucvuEntity objects.</summary>
	[Serializable]
	public partial class DmchucvuEntityFactory : EntityFactoryBase2<DmchucvuEntity> 
	{
		/// <summary>CTor</summary>
		public DmchucvuEntityFactory() : base("DmchucvuEntity", Authorize.Dal.EntityType.DmchucvuEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new DmchucvuEntity(fields); }
	}

	/// <summary>Factory to create new, empty DmphongbanEntity objects.</summary>
	[Serializable]
	public partial class DmphongbanEntityFactory : EntityFactoryBase2<DmphongbanEntity> 
	{
		/// <summary>CTor</summary>
		public DmphongbanEntityFactory() : base("DmphongbanEntity", Authorize.Dal.EntityType.DmphongbanEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new DmphongbanEntity(fields); }
	}

	/// <summary>Factory to create new, empty DmtochucEntity objects.</summary>
	[Serializable]
	public partial class DmtochucEntityFactory : EntityFactoryBase2<DmtochucEntity> 
	{
		/// <summary>CTor</summary>
		public DmtochucEntityFactory() : base("DmtochucEntity", Authorize.Dal.EntityType.DmtochucEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new DmtochucEntity(fields); }
	}

	/// <summary>Factory to create new, empty HomeShareEntity objects.</summary>
	[Serializable]
	public partial class HomeShareEntityFactory : EntityFactoryBase2<HomeShareEntity> 
	{
		/// <summary>CTor</summary>
		public HomeShareEntityFactory() : base("HomeShareEntity", Authorize.Dal.EntityType.HomeShareEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new HomeShareEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysappEntity objects.</summary>
	[Serializable]
	public partial class SysappEntityFactory : EntityFactoryBase2<SysappEntity> 
	{
		/// <summary>CTor</summary>
		public SysappEntityFactory() : base("SysappEntity", Authorize.Dal.EntityType.SysappEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysappEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysattachmentEntity objects.</summary>
	[Serializable]
	public partial class SysattachmentEntityFactory : EntityFactoryBase2<SysattachmentEntity> 
	{
		/// <summary>CTor</summary>
		public SysattachmentEntityFactory() : base("SysattachmentEntity", Authorize.Dal.EntityType.SysattachmentEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysattachmentEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysdinhdanhEntity objects.</summary>
	[Serializable]
	public partial class SysdinhdanhEntityFactory : EntityFactoryBase2<SysdinhdanhEntity> 
	{
		/// <summary>CTor</summary>
		public SysdinhdanhEntityFactory() : base("SysdinhdanhEntity", Authorize.Dal.EntityType.SysdinhdanhEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysdinhdanhEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysdvhanhchinhEntity objects.</summary>
	[Serializable]
	public partial class SysdvhanhchinhEntityFactory : EntityFactoryBase2<SysdvhanhchinhEntity> 
	{
		/// <summary>CTor</summary>
		public SysdvhanhchinhEntityFactory() : base("SysdvhanhchinhEntity", Authorize.Dal.EntityType.SysdvhanhchinhEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysdvhanhchinhEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysdvqhnEntity objects.</summary>
	[Serializable]
	public partial class SysdvqhnEntityFactory : EntityFactoryBase2<SysdvqhnEntity> 
	{
		/// <summary>CTor</summary>
		public SysdvqhnEntityFactory() : base("SysdvqhnEntity", Authorize.Dal.EntityType.SysdvqhnEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysdvqhnEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysgroupEntity objects.</summary>
	[Serializable]
	public partial class SysgroupEntityFactory : EntityFactoryBase2<SysgroupEntity> 
	{
		/// <summary>CTor</summary>
		public SysgroupEntityFactory() : base("SysgroupEntity", Authorize.Dal.EntityType.SysgroupEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysgroupEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysgroupmenuEntity objects.</summary>
	[Serializable]
	public partial class SysgroupmenuEntityFactory : EntityFactoryBase2<SysgroupmenuEntity> 
	{
		/// <summary>CTor</summary>
		public SysgroupmenuEntityFactory() : base("SysgroupmenuEntity", Authorize.Dal.EntityType.SysgroupmenuEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysgroupmenuEntity(fields); }
	}

	/// <summary>Factory to create new, empty SyslogEntity objects.</summary>
	[Serializable]
	public partial class SyslogEntityFactory : EntityFactoryBase2<SyslogEntity> 
	{
		/// <summary>CTor</summary>
		public SyslogEntityFactory() : base("SyslogEntity", Authorize.Dal.EntityType.SyslogEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SyslogEntity(fields); }
	}

	/// <summary>Factory to create new, empty SyslogactionEntity objects.</summary>
	[Serializable]
	public partial class SyslogactionEntityFactory : EntityFactoryBase2<SyslogactionEntity> 
	{
		/// <summary>CTor</summary>
		public SyslogactionEntityFactory() : base("SyslogactionEntity", Authorize.Dal.EntityType.SyslogactionEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SyslogactionEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysmenuEntity objects.</summary>
	[Serializable]
	public partial class SysmenuEntityFactory : EntityFactoryBase2<SysmenuEntity> 
	{
		/// <summary>CTor</summary>
		public SysmenuEntityFactory() : base("SysmenuEntity", Authorize.Dal.EntityType.SysmenuEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysmenuEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysRefreshtokenEntity objects.</summary>
	[Serializable]
	public partial class SysRefreshtokenEntityFactory : EntityFactoryBase2<SysRefreshtokenEntity> 
	{
		/// <summary>CTor</summary>
		public SysRefreshtokenEntityFactory() : base("SysRefreshtokenEntity", Authorize.Dal.EntityType.SysRefreshtokenEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysRefreshtokenEntity(fields); }
	}

	/// <summary>Factory to create new, empty SystaomaEntity objects.</summary>
	[Serializable]
	public partial class SystaomaEntityFactory : EntityFactoryBase2<SystaomaEntity> 
	{
		/// <summary>CTor</summary>
		public SystaomaEntityFactory() : base("SystaomaEntity", Authorize.Dal.EntityType.SystaomaEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SystaomaEntity(fields); }
	}

	/// <summary>Factory to create new, empty SystudienEntity objects.</summary>
	[Serializable]
	public partial class SystudienEntityFactory : EntityFactoryBase2<SystudienEntity> 
	{
		/// <summary>CTor</summary>
		public SystudienEntityFactory() : base("SystudienEntity", Authorize.Dal.EntityType.SystudienEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SystudienEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysunitEntity objects.</summary>
	[Serializable]
	public partial class SysunitEntityFactory : EntityFactoryBase2<SysunitEntity> 
	{
		/// <summary>CTor</summary>
		public SysunitEntityFactory() : base("SysunitEntity", Authorize.Dal.EntityType.SysunitEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysunitEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysuserEntity objects.</summary>
	[Serializable]
	public partial class SysuserEntityFactory : EntityFactoryBase2<SysuserEntity> 
	{
		/// <summary>CTor</summary>
		public SysuserEntityFactory() : base("SysuserEntity", Authorize.Dal.EntityType.SysuserEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysuserEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysusergroupEntity objects.</summary>
	[Serializable]
	public partial class SysusergroupEntityFactory : EntityFactoryBase2<SysusergroupEntity> 
	{
		/// <summary>CTor</summary>
		public SysusergroupEntityFactory() : base("SysusergroupEntity", Authorize.Dal.EntityType.SysusergroupEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysusergroupEntity(fields); }
	}

	/// <summary>Factory to create new, empty SysusermenuEntity objects.</summary>
	[Serializable]
	public partial class SysusermenuEntityFactory : EntityFactoryBase2<SysusermenuEntity> 
	{
		/// <summary>CTor</summary>
		public SysusermenuEntityFactory() : base("SysusermenuEntity", Authorize.Dal.EntityType.SysusermenuEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new SysusermenuEntity(fields); }
	}

	/// <summary>Factory to create new, empty TochucChucvuEntity objects.</summary>
	[Serializable]
	public partial class TochucChucvuEntityFactory : EntityFactoryBase2<TochucChucvuEntity> 
	{
		/// <summary>CTor</summary>
		public TochucChucvuEntityFactory() : base("TochucChucvuEntity", Authorize.Dal.EntityType.TochucChucvuEntity, false) { }
		/// <inheritdoc/>
		protected override IEntity2 CreateImpl(IEntityFields2 fields) { return new TochucChucvuEntity(fields); }
	}

	/// <summary>Factory to create new, empty Entity objects based on the entity type specified. Uses  entity specific factory objects</summary>
	[Serializable]
	public partial class GeneralEntityFactory
	{
		/// <summary>Creates a new, empty Entity object of the type specified</summary>
		/// <param name="entityTypeToCreate">The entity type to create.</param>
		/// <returns>A new, empty Entity object.</returns>
		public static IEntity2 Create(Authorize.Dal.EntityType entityTypeToCreate)
		{
			var factoryToUse = EntityFactoryFactory.GetFactory(entityTypeToCreate);
			IEntity2 toReturn = null;
			if(factoryToUse != null)
			{
				toReturn = factoryToUse.Create();
			}
			return toReturn;
		}		
	}
		
	/// <summary>Class which is used to obtain the entity factory based on the .NET type of the entity. </summary>
	[Serializable]
	public static class EntityFactoryFactory
	{
		private static Dictionary<Type, IEntityFactory2> _factoryPerType = new Dictionary<Type, IEntityFactory2>();

		/// <summary>Initializes the <see cref="EntityFactoryFactory"/> class.</summary>
		static EntityFactoryFactory()
		{
			foreach(int entityTypeValue in Enum.GetValues(typeof(Authorize.Dal.EntityType)))
			{
				var factory = GetFactory((Authorize.Dal.EntityType)entityTypeValue);
				_factoryPerType.Add(factory.ForEntityType ?? factory.Create().GetType(), factory);
			}
		}

		/// <summary>Gets the factory of the entity with the .NET type specified</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>factory to use or null if not found</returns>
		public static IEntityFactory2 GetFactory(Type typeOfEntity) { return _factoryPerType.GetValue(typeOfEntity); }

		/// <summary>Gets the factory of the entity with the Authorize.Dal.EntityType specified</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>factory to use or null if not found</returns>
		public static IEntityFactory2 GetFactory(Authorize.Dal.EntityType typeOfEntity)
		{
			switch(typeOfEntity)
			{
				case Authorize.Dal.EntityType.DangkychiaseEntity:
					return new DangkychiaseEntityFactory();
				case Authorize.Dal.EntityType.DmchucvuEntity:
					return new DmchucvuEntityFactory();
				case Authorize.Dal.EntityType.DmphongbanEntity:
					return new DmphongbanEntityFactory();
				case Authorize.Dal.EntityType.DmtochucEntity:
					return new DmtochucEntityFactory();
				case Authorize.Dal.EntityType.HomeShareEntity:
					return new HomeShareEntityFactory();
				case Authorize.Dal.EntityType.SysappEntity:
					return new SysappEntityFactory();
				case Authorize.Dal.EntityType.SysattachmentEntity:
					return new SysattachmentEntityFactory();
				case Authorize.Dal.EntityType.SysdinhdanhEntity:
					return new SysdinhdanhEntityFactory();
				case Authorize.Dal.EntityType.SysdvhanhchinhEntity:
					return new SysdvhanhchinhEntityFactory();
				case Authorize.Dal.EntityType.SysdvqhnEntity:
					return new SysdvqhnEntityFactory();
				case Authorize.Dal.EntityType.SysgroupEntity:
					return new SysgroupEntityFactory();
				case Authorize.Dal.EntityType.SysgroupmenuEntity:
					return new SysgroupmenuEntityFactory();
				case Authorize.Dal.EntityType.SyslogEntity:
					return new SyslogEntityFactory();
				case Authorize.Dal.EntityType.SyslogactionEntity:
					return new SyslogactionEntityFactory();
				case Authorize.Dal.EntityType.SysmenuEntity:
					return new SysmenuEntityFactory();
				case Authorize.Dal.EntityType.SysRefreshtokenEntity:
					return new SysRefreshtokenEntityFactory();
				case Authorize.Dal.EntityType.SystaomaEntity:
					return new SystaomaEntityFactory();
				case Authorize.Dal.EntityType.SystudienEntity:
					return new SystudienEntityFactory();
				case Authorize.Dal.EntityType.SysunitEntity:
					return new SysunitEntityFactory();
				case Authorize.Dal.EntityType.SysuserEntity:
					return new SysuserEntityFactory();
				case Authorize.Dal.EntityType.SysusergroupEntity:
					return new SysusergroupEntityFactory();
				case Authorize.Dal.EntityType.SysusermenuEntity:
					return new SysusermenuEntityFactory();
				case Authorize.Dal.EntityType.TochucChucvuEntity:
					return new TochucChucvuEntityFactory();
				default:
					return null;
			}
		}
	}
		
	/// <summary>Element creator for creating project elements from somewhere else, like inside Linq providers.</summary>
	public class ElementCreator : ElementCreatorBase, IElementCreator2
	{
		/// <summary>Gets the factory of the Entity type with the Authorize.Dal.EntityType value passed in</summary>
		/// <param name="entityTypeValue">The entity type value.</param>
		/// <returns>the entity factory of the entity type or null if not found</returns>
		public IEntityFactory2 GetFactory(int entityTypeValue) { return (IEntityFactory2)this.GetFactoryImpl(entityTypeValue); }
		
		/// <summary>Gets the factory of the Entity type with the .NET type passed in</summary>
		/// <param name="typeOfEntity">The type of entity.</param>
		/// <returns>the entity factory of the entity type or null if not found</returns>
		public IEntityFactory2 GetFactory(Type typeOfEntity) { return (IEntityFactory2)this.GetFactoryImpl(typeOfEntity); }

		/// <summary>Creates a new resultset fields object with the number of field slots reserved as specified</summary>
		/// <param name="numberOfFields">The number of fields.</param>
		/// <returns>ready to use resultsetfields object</returns>
		public IEntityFields2 CreateResultsetFields(int numberOfFields) { return new ResultsetFields(numberOfFields); }
		
		/// <inheritdoc/>
		public override IInheritanceInfoProvider ObtainInheritanceInfoProviderInstance() { return ModelInfoProviderSingleton.GetInstance(); }

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand) { return new DynamicRelation(leftOperand); }

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand, JoinHint joinType, DerivedTableDefinition rightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, rightOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(IEntityFieldCore leftOperand, JoinHint joinType, DerivedTableDefinition rightOperand, string aliasLeftOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, rightOperand, aliasLeftOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(DerivedTableDefinition leftOperand, JoinHint joinType, string rightOperandEntityName, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, (Authorize.Dal.EntityType)Enum.Parse(typeof(Authorize.Dal.EntityType), rightOperandEntityName, false), aliasRightOperand, onClause);
		}

		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(string leftOperandEntityName, JoinHint joinType, string rightOperandEntityName, string aliasLeftOperand, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation((Authorize.Dal.EntityType)Enum.Parse(typeof(Authorize.Dal.EntityType), leftOperandEntityName, false), joinType, (Authorize.Dal.EntityType)Enum.Parse(typeof(Authorize.Dal.EntityType), rightOperandEntityName, false), aliasLeftOperand, aliasRightOperand, onClause);
		}
		
		/// <inheritdoc/>
		public override IDynamicRelation CreateDynamicRelation(IEntityFieldCore leftOperand, JoinHint joinType, string rightOperandEntityName, string aliasLeftOperand, string aliasRightOperand, IPredicate onClause)
		{
			return new DynamicRelation(leftOperand, joinType, (Authorize.Dal.EntityType)Enum.Parse(typeof(Authorize.Dal.EntityType), rightOperandEntityName, false), aliasLeftOperand, aliasRightOperand, onClause);
		}
		
		/// <inheritdoc/>
		protected override IEntityFactoryCore GetFactoryImpl(int entityTypeValue) { return EntityFactoryFactory.GetFactory((Authorize.Dal.EntityType)entityTypeValue); }

		/// <inheritdoc/>
		protected override IEntityFactoryCore GetFactoryImpl(Type typeOfEntity) { return EntityFactoryFactory.GetFactory(typeOfEntity);	}

	}
}
