//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.QTHTGis.Dal.HelperClasses;
using App.QTHTGis.Dal.FactoryClasses;
using App.QTHTGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.QTHTGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Logdag'.<br/><br/></summary>
	[Serializable]
	public partial class LogdagEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static LogdagEntityStaticMetaData _staticMetaData = new LogdagEntityStaticMetaData();
		private static LogdagRelations _relationsFactory = new LogdagRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class LogdagEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public LogdagEntityStaticMetaData()
			{
				SetEntityCoreInfo("LogdagEntity", InheritanceHierarchyType.None, false, (int)App.QTHTGis.Dal.EntityType.LogdagEntity, typeof(LogdagEntity), typeof(LogdagEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static LogdagEntity()
		{
		}

		/// <summary> CTor</summary>
		public LogdagEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public LogdagEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this LogdagEntity</param>
		public LogdagEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Logdag which data should be fetched into this Logdag object</param>
		public LogdagEntity(System.Int64 id) : this(id, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="id">PK value for Logdag which data should be fetched into this Logdag object</param>
		/// <param name="validator">The custom validator object for this LogdagEntity</param>
		public LogdagEntity(System.Int64 id, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Id = id;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected LogdagEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this LogdagEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static LogdagRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Appid property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."appid".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Appid
		{
			get { return (System.String)GetValue((int)LogdagFieldIndex.Appid, true); }
			set	{ SetValue((int)LogdagFieldIndex.Appid, value); }
		}

		/// <summary>The Banghihientai property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."banghihientai".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> Banghihientai
		{
			get { return (Nullable<System.Int64>)GetValue((int)LogdagFieldIndex.Banghihientai, false); }
			set	{ SetValue((int)LogdagFieldIndex.Banghihientai, value); }
		}

		/// <summary>The Dagid property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."dagid".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Dagid
		{
			get { return (System.String)GetValue((int)LogdagFieldIndex.Dagid, true); }
			set	{ SetValue((int)LogdagFieldIndex.Dagid, value); }
		}

		/// <summary>The Id property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."id".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, true</remarks>
		public virtual System.Int64 Id
		{
			get { return (System.Int64)GetValue((int)LogdagFieldIndex.Id, true); }
			set { SetValue((int)LogdagFieldIndex.Id, value); }		}

		/// <summary>The Inserted property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."inserted".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> Inserted
		{
			get { return (Nullable<System.Int64>)GetValue((int)LogdagFieldIndex.Inserted, false); }
			set	{ SetValue((int)LogdagFieldIndex.Inserted, value); }
		}

		/// <summary>The Ngaychay property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."ngaychay".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Ngaychay
		{
			get { return (Nullable<System.DateTime>)GetValue((int)LogdagFieldIndex.Ngaychay, false); }
			set	{ SetValue((int)LogdagFieldIndex.Ngaychay, value); }
		}

		/// <summary>The Ngayketthuc property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."ngayketthuc".<br/>Table field type characteristics (type, precision, scale, length): Timestamp, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> Ngayketthuc
		{
			get { return (Nullable<System.DateTime>)GetValue((int)LogdagFieldIndex.Ngayketthuc, false); }
			set	{ SetValue((int)LogdagFieldIndex.Ngayketthuc, value); }
		}

		/// <summary>The Nguon property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."nguon".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Nguon
		{
			get { return (System.String)GetValue((int)LogdagFieldIndex.Nguon, true); }
			set	{ SetValue((int)LogdagFieldIndex.Nguon, value); }
		}

		/// <summary>The Pagenumber property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."pagenumber".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> Pagenumber
		{
			get { return (Nullable<System.Int64>)GetValue((int)LogdagFieldIndex.Pagenumber, false); }
			set	{ SetValue((int)LogdagFieldIndex.Pagenumber, value); }
		}

		/// <summary>The Pagesize property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."pagesize".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> Pagesize
		{
			get { return (Nullable<System.Int64>)GetValue((int)LogdagFieldIndex.Pagesize, false); }
			set	{ SetValue((int)LogdagFieldIndex.Pagesize, value); }
		}

		/// <summary>The Tinhtrang property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."tinhtrang".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 2000.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Tinhtrang
		{
			get { return (System.String)GetValue((int)LogdagFieldIndex.Tinhtrang, true); }
			set	{ SetValue((int)LogdagFieldIndex.Tinhtrang, value); }
		}

		/// <summary>The Tongbanghinguon property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."tongbanghinguon".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> Tongbanghinguon
		{
			get { return (Nullable<System.Int64>)GetValue((int)LogdagFieldIndex.Tongbanghinguon, false); }
			set	{ SetValue((int)LogdagFieldIndex.Tongbanghinguon, value); }
		}

		/// <summary>The Trung property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."trung".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> Trung
		{
			get { return (Nullable<System.Int64>)GetValue((int)LogdagFieldIndex.Trung, false); }
			set	{ SetValue((int)LogdagFieldIndex.Trung, value); }
		}

		/// <summary>The Updated property of the Entity Logdag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "logdag"."updated".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int64> Updated
		{
			get { return (Nullable<System.Int64>)GetValue((int)LogdagFieldIndex.Updated, false); }
			set	{ SetValue((int)LogdagFieldIndex.Updated, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.QTHTGis.Dal
{
	public enum LogdagFieldIndex
	{
		///<summary>Appid. </summary>
		Appid,
		///<summary>Banghihientai. </summary>
		Banghihientai,
		///<summary>Dagid. </summary>
		Dagid,
		///<summary>Id. </summary>
		Id,
		///<summary>Inserted. </summary>
		Inserted,
		///<summary>Ngaychay. </summary>
		Ngaychay,
		///<summary>Ngayketthuc. </summary>
		Ngayketthuc,
		///<summary>Nguon. </summary>
		Nguon,
		///<summary>Pagenumber. </summary>
		Pagenumber,
		///<summary>Pagesize. </summary>
		Pagesize,
		///<summary>Tinhtrang. </summary>
		Tinhtrang,
		///<summary>Tongbanghinguon. </summary>
		Tongbanghinguon,
		///<summary>Trung. </summary>
		Trung,
		///<summary>Updated. </summary>
		Updated,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.QTHTGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Logdag. </summary>
	public partial class LogdagRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticLogdagRelations
	{

		/// <summary>CTor</summary>
		static StaticLogdagRelations() { }
	}
}
