//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.QTHTGis.Dal.HelperClasses;
using App.QTHTGis.Dal.FactoryClasses;
using App.QTHTGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.QTHTGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Sysgroupmenu'.<br/><br/></summary>
	[Serializable]
	public partial class SysgroupmenuEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private SysgroupEntity _sysgroup;
		private SysmenuEntity _sysmenu;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysgroupmenuEntityStaticMetaData _staticMetaData = new SysgroupmenuEntityStaticMetaData();
		private static SysgroupmenuRelations _relationsFactory = new SysgroupmenuRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Sysgroup</summary>
			public static readonly string Sysgroup = "Sysgroup";
			/// <summary>Member name Sysmenu</summary>
			public static readonly string Sysmenu = "Sysmenu";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysgroupmenuEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysgroupmenuEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysgroupmenuEntity", InheritanceHierarchyType.None, false, (int)App.QTHTGis.Dal.EntityType.SysgroupmenuEntity, typeof(SysgroupmenuEntity), typeof(SysgroupmenuEntityFactory), false);
				AddNavigatorMetaData<SysgroupmenuEntity, SysgroupEntity>("Sysgroup", "Sysgroupmenus", (a, b) => a._sysgroup = b, a => a._sysgroup, (a, b) => a.Sysgroup = b, App.QTHTGis.Dal.RelationClasses.StaticSysgroupmenuRelations.SysgroupEntityUsingGroupidStatic, ()=>new SysgroupmenuRelations().SysgroupEntityUsingGroupid, null, new int[] { (int)SysgroupmenuFieldIndex.Groupid }, null, true, (int)App.QTHTGis.Dal.EntityType.SysgroupEntity);
				AddNavigatorMetaData<SysgroupmenuEntity, SysmenuEntity>("Sysmenu", "Sysgroupmenus", (a, b) => a._sysmenu = b, a => a._sysmenu, (a, b) => a.Sysmenu = b, App.QTHTGis.Dal.RelationClasses.StaticSysgroupmenuRelations.SysmenuEntityUsingMenuidStatic, ()=>new SysgroupmenuRelations().SysmenuEntityUsingMenuid, null, new int[] { (int)SysgroupmenuFieldIndex.Menuid }, null, true, (int)App.QTHTGis.Dal.EntityType.SysmenuEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static SysgroupmenuEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysgroupmenuEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysgroupmenuEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysgroupmenuEntity</param>
		public SysgroupmenuEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="groupid">PK value for Sysgroupmenu which data should be fetched into this Sysgroupmenu object</param>
		/// <param name="menuid">PK value for Sysgroupmenu which data should be fetched into this Sysgroupmenu object</param>
		public SysgroupmenuEntity(System.Int64 groupid, System.Int64 menuid) : this(groupid, menuid, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="groupid">PK value for Sysgroupmenu which data should be fetched into this Sysgroupmenu object</param>
		/// <param name="menuid">PK value for Sysgroupmenu which data should be fetched into this Sysgroupmenu object</param>
		/// <param name="validator">The custom validator object for this SysgroupmenuEntity</param>
		public SysgroupmenuEntity(System.Int64 groupid, System.Int64 menuid, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Groupid = groupid;
			this.Menuid = menuid;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysgroupmenuEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Sysgroup' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSysgroup() { return CreateRelationInfoForNavigator("Sysgroup"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Sysmenu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSysmenu() { return CreateRelationInfoForNavigator("Sysmenu"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysgroupmenuEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysgroupmenuRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Sysgroup' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSysgroup { get { return _staticMetaData.GetPrefetchPathElement("Sysgroup", CommonEntityBase.CreateEntityCollection<SysgroupEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Sysmenu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSysmenu { get { return _staticMetaData.GetPrefetchPathElement("Sysmenu", CommonEntityBase.CreateEntityCollection<SysmenuEntity>()); } }

		/// <summary>The Function property of the Entity Sysgroupmenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysgroupmenu"."function".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Function
		{
			get { return (System.String)GetValue((int)SysgroupmenuFieldIndex.Function, true); }
			set	{ SetValue((int)SysgroupmenuFieldIndex.Function, value); }
		}

		/// <summary>The Groupid property of the Entity Sysgroupmenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysgroupmenu"."groupid".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int64 Groupid
		{
			get { return (System.Int64)GetValue((int)SysgroupmenuFieldIndex.Groupid, true); }
			set	{ SetValue((int)SysgroupmenuFieldIndex.Groupid, value); }
		}

		/// <summary>The Menuid property of the Entity Sysgroupmenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysgroupmenu"."menuid".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int64 Menuid
		{
			get { return (System.Int64)GetValue((int)SysgroupmenuFieldIndex.Menuid, true); }
			set	{ SetValue((int)SysgroupmenuFieldIndex.Menuid, value); }
		}

		/// <summary>Gets / sets related entity of type 'SysgroupEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual SysgroupEntity Sysgroup
		{
			get { return _sysgroup; }
			set { SetSingleRelatedEntityNavigator(value, "Sysgroup"); }
		}

		/// <summary>Gets / sets related entity of type 'SysmenuEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual SysmenuEntity Sysmenu
		{
			get { return _sysmenu; }
			set { SetSingleRelatedEntityNavigator(value, "Sysmenu"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.QTHTGis.Dal
{
	public enum SysgroupmenuFieldIndex
	{
		///<summary>Function. </summary>
		Function,
		///<summary>Groupid. </summary>
		Groupid,
		///<summary>Menuid. </summary>
		Menuid,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.QTHTGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Sysgroupmenu. </summary>
	public partial class SysgroupmenuRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between SysgroupmenuEntity and SysgroupEntity over the m:1 relation they have, using the relation between the fields: Sysgroupmenu.Groupid - Sysgroup.Groupid</summary>
		public virtual IEntityRelation SysgroupEntityUsingGroupid
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Sysgroup", false, new[] { SysgroupFields.Groupid, SysgroupmenuFields.Groupid }); }
		}

		/// <summary>Returns a new IEntityRelation object, between SysgroupmenuEntity and SysmenuEntity over the m:1 relation they have, using the relation between the fields: Sysgroupmenu.Menuid - Sysmenu.Menuid</summary>
		public virtual IEntityRelation SysmenuEntityUsingMenuid
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Sysmenu", false, new[] { SysmenuFields.Menuid, SysgroupmenuFields.Menuid }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysgroupmenuRelations
	{
		internal static readonly IEntityRelation SysgroupEntityUsingGroupidStatic = new SysgroupmenuRelations().SysgroupEntityUsingGroupid;
		internal static readonly IEntityRelation SysmenuEntityUsingMenuidStatic = new SysgroupmenuRelations().SysmenuEntityUsingMenuid;

		/// <summary>CTor</summary>
		static StaticSysgroupmenuRelations() { }
	}
}
