//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.10.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using App.QTHTGis.Dal.HelperClasses;
using App.QTHTGis.Dal.FactoryClasses;
using App.QTHTGis.Dal.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace App.QTHTGis.Dal.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Sysusermenu'.<br/><br/></summary>
	[Serializable]
	public partial class SysusermenuEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private SysmenuEntity _sysmenu;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static SysusermenuEntityStaticMetaData _staticMetaData = new SysusermenuEntityStaticMetaData();
		private static SysusermenuRelations _relationsFactory = new SysusermenuRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Sysmenu</summary>
			public static readonly string Sysmenu = "Sysmenu";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SysusermenuEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SysusermenuEntityStaticMetaData()
			{
				SetEntityCoreInfo("SysusermenuEntity", InheritanceHierarchyType.None, false, (int)App.QTHTGis.Dal.EntityType.SysusermenuEntity, typeof(SysusermenuEntity), typeof(SysusermenuEntityFactory), false);
				AddNavigatorMetaData<SysusermenuEntity, SysmenuEntity>("Sysmenu", "Sysusermenus", (a, b) => a._sysmenu = b, a => a._sysmenu, (a, b) => a.Sysmenu = b, App.QTHTGis.Dal.RelationClasses.StaticSysusermenuRelations.SysmenuEntityUsingMenuidStatic, ()=>new SysusermenuRelations().SysmenuEntityUsingMenuid, null, new int[] { (int)SysusermenuFieldIndex.Menuid }, null, true, (int)App.QTHTGis.Dal.EntityType.SysmenuEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static SysusermenuEntity()
		{
		}

		/// <summary> CTor</summary>
		public SysusermenuEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SysusermenuEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SysusermenuEntity</param>
		public SysusermenuEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="menuid">PK value for Sysusermenu which data should be fetched into this Sysusermenu object</param>
		/// <param name="userid">PK value for Sysusermenu which data should be fetched into this Sysusermenu object</param>
		public SysusermenuEntity(System.Int64 menuid, System.Int64 userid) : this(menuid, userid, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="menuid">PK value for Sysusermenu which data should be fetched into this Sysusermenu object</param>
		/// <param name="userid">PK value for Sysusermenu which data should be fetched into this Sysusermenu object</param>
		/// <param name="validator">The custom validator object for this SysusermenuEntity</param>
		public SysusermenuEntity(System.Int64 menuid, System.Int64 userid, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Menuid = menuid;
			this.Userid = userid;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SysusermenuEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Sysmenu' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSysmenu() { return CreateRelationInfoForNavigator("Sysmenu"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SysusermenuEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SysusermenuRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Sysmenu' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSysmenu { get { return _staticMetaData.GetPrefetchPathElement("Sysmenu", CommonEntityBase.CreateEntityCollection<SysmenuEntity>()); } }

		/// <summary>The Function property of the Entity Sysusermenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysusermenu"."function".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Function
		{
			get { return (System.String)GetValue((int)SysusermenuFieldIndex.Function, true); }
			set	{ SetValue((int)SysusermenuFieldIndex.Function, value); }
		}

		/// <summary>The Menuid property of the Entity Sysusermenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysusermenu"."menuid".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int64 Menuid
		{
			get { return (System.Int64)GetValue((int)SysusermenuFieldIndex.Menuid, true); }
			set	{ SetValue((int)SysusermenuFieldIndex.Menuid, value); }
		}

		/// <summary>The Userid property of the Entity Sysusermenu<br/><br/></summary>
		/// <remarks>Mapped on  table field: "sysusermenu"."userid".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int64 Userid
		{
			get { return (System.Int64)GetValue((int)SysusermenuFieldIndex.Userid, true); }
			set	{ SetValue((int)SysusermenuFieldIndex.Userid, value); }
		}

		/// <summary>Gets / sets related entity of type 'SysmenuEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual SysmenuEntity Sysmenu
		{
			get { return _sysmenu; }
			set { SetSingleRelatedEntityNavigator(value, "Sysmenu"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace App.QTHTGis.Dal
{
	public enum SysusermenuFieldIndex
	{
		///<summary>Function. </summary>
		Function,
		///<summary>Menuid. </summary>
		Menuid,
		///<summary>Userid. </summary>
		Userid,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace App.QTHTGis.Dal.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Sysusermenu. </summary>
	public partial class SysusermenuRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between SysusermenuEntity and SysmenuEntity over the m:1 relation they have, using the relation between the fields: Sysusermenu.Menuid - Sysmenu.Menuid</summary>
		public virtual IEntityRelation SysmenuEntityUsingMenuid
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Sysmenu", false, new[] { SysmenuFields.Menuid, SysusermenuFields.Menuid }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSysusermenuRelations
	{
		internal static readonly IEntityRelation SysmenuEntityUsingMenuidStatic = new SysusermenuRelations().SysmenuEntityUsingMenuid;

		/// <summary>CTor</summary>
		static StaticSysusermenuRelations() { }
	}
}
